
var Libvoikko = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Libvoikko) {
  Libvoikko = Libvoikko || {};

var e;e||(e=typeof Libvoikko !== 'undefined' ? Libvoikko : {});e.lb||(e.lb=0,e.Tb=0);e.lb++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.Ga?e.Va[a].loaded=c.loaded:(d.Ga=!0,e.Va||(e.Va={}),e.Va[a]={loaded:c.loaded,total:f});var g=f=c=0,m;for(m in e.Va){var h=e.Va[m];c+=h.total;f+=h.loaded;g++}c=Math.ceil(c*e.lb/g);e.setStatus&&e.setStatus("Downloading data... ("+f+"/"+c+")")}else!e.Va&&e.setStatus&&e.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){e.Tb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);var d=e.getMemory(c.length);e.HEAPU8.set(c,
d);b.prototype.Sb=e.HEAPU8.subarray(d,d+c.length);c=a.files;for(d=0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();e.removeRunDependency("datafile_js/libvoikko.data")}e.FS_createPath("/","5",!0,!0);e.FS_createPath("/5","mor-standard",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.Sb.subarray(this.start,this.end))},finish:function(a){e.FS_createDataFile(this.name,null,a,!0,!0,
!0);e.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].audio)).open("GET",d[f].filename);e.addRunDependency("datafile_js/libvoikko.data");e.Jb||(e.Jb={});e.Jb["js/libvoikko.data"]={se:!1};l?(c(l),l=null):h=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=e.locateFile?e.locateFile("libvoikko.data",""):"libvoikko.data",g=a.ve,h=null,l=e.getPreloadedPackage?e.getPreloadedPackage(f,g):null;l||
b(f,g,function(a){h?(h(a),h=null):l=a},c);e.calledRun?d():(e.preRun||(e.preRun=[]),e.preRun.push(d))})({files:[{start:0,audio:0,end:11360,filename:"/5/mor-standard/autocorr.vfst"},{start:11360,audio:0,end:3961160,filename:"/5/mor-standard/mor.vfst"},{start:3961160,audio:0,end:3961524,filename:"/5/mor-standard/index.txt"}],remote_package_size:3961524,package_uuid:"e397701e-955c-49fd-9b44-3a48c09a2199"});var ba={},p;for(p in e)e.hasOwnProperty(p)&&(ba[p]=e[p]);e.arguments=[];e.thisProgram="./this.program";
e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ca=!1,q=!1,da=!1,ea=!1;ca="object"===typeof window;q="function"===typeof importScripts;da="object"===typeof process&&"function"===typeof require&&!ca&&!q;ea=!ca&&!da&&!q;var t="";
if(da){t=__dirname+"/";var fa,ha;e.read=function(a,b){fa||(fa=require("fs"));ha||(ha=require("path"));a=ha.normalize(a);a=fa.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof ia))throw a;});process.on("unhandledRejection",v);e.quit=function(a){process.exit(a)};
e.inspect=function(){return"[Emscripten Module object]"}}else if(ea)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ca||q)q?t=self.location.href:document.currentScript&&
(t=document.currentScript.src),_scriptDir&&(t=_scriptDir),0!==t.indexOf("blob:")?t=t.substr(0,t.lastIndexOf("/")+1):t="",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ja=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),k=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ja);for(p in ba)ba.hasOwnProperty(p)&&(e[p]=ba[p]);ba=void 0;var ka={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}},la=!1;
function assert(a,b){a||v("Assertion failed: "+b)}function ma(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}var ra={stackSave:function(){na()},stackRestore:function(){oa()},arrayToC:function(a){var b=pa(a.length);w.set(a,b);return b},stringToC:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=pa(c);qa(a,x,b,c)}return b}},sa={string:ra.stringToC,array:ra.arrayToC};
function y(a,b,c){c=c||[];var d=c.every(function(a){return"number"===a});return"string"!==b&&d?ma(a):function(){var d=c,g=arguments,h=ma(a),l=[],n=0;if(g)for(var r=0;r<g.length;r++){var u=sa[d[r]];u?(0===n&&(n=na()),l[r]=u(g[r])):l[r]=g[r]}d=h.apply(null,l);d="string"===b?ta(d):"boolean"===b?!!d:d;0!==n&&oa(n);return d}}
function B(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return w[a>>0];case "i8":return w[a>>0];case "i16":return ua[a>>1];case "i32":return C[a>>2];case "i64":return C[a>>2];case "float":return va[a>>2];case "double":return wa[a>>3];default:v("invalid type for getValue: "+b)}return null}function xa(a){if(ya)var b=D(a);else b=C[za>>2],a=b+a+15&-16,a<=E?C[za>>2]=a:b=0;return b}
function ta(a){var b;if(0===b||!a)return"";for(var c=0,d,f=0;;){d=x[a+f>>0];c|=d;if(0==d&&!b)break;f++;if(b&&f==b)break}b||(b=f);d="";if(128>c){for(;0<b;)c=String.fromCharCode.apply(String,x.subarray(a,a+Math.min(b,1024))),d=d?d+c:c,a+=1024,b-=1024;return d}return F(a)}var Aa="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function Ba(a,b){for(var c=b;a[c];)++c;if(16<c-b&&a.subarray&&Aa)return Aa.decode(a.subarray(b,c));for(c="";;){var d=a[b++];if(!d)return c;if(d&128){var f=a[b++]&63;if(192==(d&224))c+=String.fromCharCode((d&31)<<6|f);else{var g=a[b++]&63;d=224==(d&240)?(d&15)<<12|f<<6|g:(d&7)<<18|f<<12|g<<6|a[b++]&63;65536>d?c+=String.fromCharCode(d):(d-=65536,c+=String.fromCharCode(55296|d>>10,56320|d&1023))}}else c+=String.fromCharCode(d)}}function F(a){return Ba(x,a)}
function qa(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function Ca(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:2097151>=d?b+4:67108863>=d?b+5:b+6}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,w,x,ua,C,va,wa;
function Da(){e.HEAP8=w=new Int8Array(buffer);e.HEAP16=ua=new Int16Array(buffer);e.HEAP32=C=new Int32Array(buffer);e.HEAPU8=x=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=va=new Float32Array(buffer);e.HEAPF64=wa=new Float64Array(buffer)}var Ea=1024,za=39792;
function Fa(){v("Cannot enlarge memory arrays. Either (1) compile with  -s TOTAL_MEMORY=X  with X higher than the current value "+E+", (2) compile with  -s ALLOW_MEMORY_GROWTH=1  which allows increasing the size at runtime, or (3) if you want malloc to return NULL (0) instead of this abort, compile with  -s ABORTING_MALLOC=0 ")}var E=e.TOTAL_MEMORY||16777216;5242880>E&&k("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+E+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:("object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(e.wasmMemory=new WebAssembly.Memory({initial:E/65536,maximum:E/65536}),buffer=e.wasmMemory.buffer):buffer=new ArrayBuffer(E),e.buffer=buffer);Da();C[za>>2]=5282928;function Ga(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Db;"number"===typeof c?void 0===b.kb?e.dynCall_v(c):e.dynCall_vi(c,b.kb):c(void 0===b.kb?null:b.kb)}}}var Ha=[],Ia=[],Ja=[],Ka=[],La=[],ya=!1;
function Ma(){var a=e.preRun.shift();Ha.unshift(a)}var Na=0,Oa=null,Pa=null;function Qa(){Na++;e.monitorRunDependencies&&e.monitorRunDependencies(Na)}function Ra(){Na--;e.monitorRunDependencies&&e.monitorRunDependencies(Na);if(0==Na&&(null!==Oa&&(clearInterval(Oa),Oa=null),Pa)){var a=Pa;Pa=null;a()}}e.preloadedImages={};e.preloadedAudios={};
function Sa(){var a=Ta;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Ta="libvoikko.wasm";if(!Sa()){var Ua=Ta;Ta=e.locateFile?e.locateFile(Ua,t):t+Ua}function Va(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(Ta);throw"both async and sync fetching of the wasm failed";}catch(a){v(a)}}
function Wa(){return e.wasmBinary||!ca&&!q||"function"!==typeof fetch?new Promise(function(a){a(Va())}):fetch(Ta,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Ta+"'";return a.arrayBuffer()}).catch(function(){return Va()})}
function Xa(a){function b(a){a=a.exports;if(a.memory){var b=a.memory,c=e.buffer;b.byteLength<c.byteLength&&k("the new buffer in mergeMemory is smaller than the previous one. in native wasm, we should grow memory here");c=new Int8Array(c);(new Int8Array(b)).set(c);e.buffer=buffer=b;Da()}e.asm=a;Ra("wasm-instantiate")}function c(a){b(a.instance)}function d(a){Wa().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){k("failed to asynchronously prepare wasm: "+a);v(a)})}if("object"!==
typeof WebAssembly)return k("no native wasm support detected"),!1;if(!(e.wasmMemory instanceof WebAssembly.Memory))return k("no native wasm Memory in use"),!1;a.memory=e.wasmMemory;var f={global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,env:a,asm2wasm:ka,parent:e};Qa("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(f,b)}catch(g){return k("Module.instantiateWasm callback failed with error: "+g),!1}e.wasmBinary||"function"!==typeof WebAssembly.instantiateStreaming||Sa()||"function"!==
typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(Ta,{credentials:"same-origin"}),f).then(c,function(a){k("wasm streaming compile failed: "+a);k("falling back to ArrayBuffer instantiation");d(c)});return{}}e.reallocBuffer=function(a){0<a%65536&&(a+=65536-a%65536);var b=e.buffer.byteLength;try{var c=-1!==e.wasmMemory.grow((a-b)/65536)?e.buffer=e.wasmMemory.buffer:null}catch(d){c=null}return c};
e.asm=function(a,b){if(!b.table){a=e.wasmTableSize;var c=e.wasmMaxTableSize;b.table="object"===typeof WebAssembly&&"function"===typeof WebAssembly.Table?void 0!==c?new WebAssembly.Table({initial:a,maximum:c,element:"anyfunc"}):new WebAssembly.Table({initial:a,element:"anyfunc"}):Array(a);e.wasmTable=b.table}b.__memory_base||(b.__memory_base=e.STATIC_BASE);b.__table_base||(b.__table_base=0);return Xa(b)};Ea=1024;Ia.push({Db:function(){Ya()}},{Db:function(){Za()}});e.STATIC_BASE=Ea;e.STATIC_BUMP=39024;
var G={};
function $a(a){if($a.Ga){var b=C[a>>2];var c=C[b>>2]}else $a.Ga=!0,G.USER=G.LOGNAME="web_user",G.PATH="/",G.PWD="/",G.HOME="/home/web_user",G.LANG="C.UTF-8",G._=e.thisProgram,c=xa(1024),b=xa(256),C[b>>2]=c,C[a>>2]=b;a=[];var d=0,f;for(f in G)if("string"===typeof G[f]){var g=f+"="+G[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,l=0;l<d.length;++l)w[h++>>0]=d.charCodeAt(l);w[h>>0]=0;C[b+4*f>>2]=c;c+=g.length+
1}C[b+4*a.length>>2]=0}function ab(a){e.___errno_location&&(C[e.___errno_location()>>2]=a);return a}function bb(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function cb(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=bb(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function db(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function eb(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function fb(){var a=Array.prototype.slice.call(arguments,0);return cb(a.join("/"))}function H(a,b){return cb(a+"/"+b)}
function gb(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=bb(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var hb=[];function ib(a,b){hb[a]={input:[],output:[],Xa:b};jb(a,kb)}
var kb={open:function(a){var b=hb[a.node.rdev];if(!b)throw new I(J.ib);a.tty=b;a.seekable=!1},close:function(a){a.tty.Xa.flush(a.tty)},flush:function(a){a.tty.Xa.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Xa.Fb)throw new I(J.vb);for(var f=0,g=0;g<d;g++){try{var h=a.tty.Xa.Fb(a.tty)}catch(l){throw new I(J.sb);}if(void 0===h&&0===f)throw new I(J.Lb);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Xa.ob)throw new I(J.vb);
try{for(var f=0;f<d;f++)a.tty.Xa.ob(a.tty,b[c+f])}catch(g){throw new I(J.sb);}d&&(a.node.timestamp=Date.now());return f}},ob={Fb:function(a){if(!a.input.length){var b=null;if(da){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=nb(b,!0)}return a.input.shift()},ob:function(a,b){null===b||10===b?(ja(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ja(Ba(a.output,0)),a.output=[])}},pb={ob:function(a,b){null===b||10===b?(k(Ba(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(k(Ba(a.output,0)),a.output=[])}},K={Oa:null,La:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(J.Ob);K.Oa||(K.Oa={dir:{node:{Na:K.Da.Na,Ja:K.Da.Ja,lookup:K.Da.lookup,Za:K.Da.Za,rename:K.Da.rename,unlink:K.Da.unlink,rmdir:K.Da.rmdir,readdir:K.Da.readdir,symlink:K.Da.symlink},stream:{Pa:K.Ea.Pa}},file:{node:{Na:K.Da.Na,Ja:K.Da.Ja},stream:{Pa:K.Ea.Pa,read:K.Ea.read,write:K.Ea.write,wb:K.Ea.wb,eb:K.Ea.eb,
fb:K.Ea.fb}},link:{node:{Na:K.Da.Na,Ja:K.Da.Ja,readlink:K.Da.readlink},stream:{}},zb:{node:{Na:K.Da.Na,Ja:K.Da.Ja},stream:qb}});c=rb(a,b,c,d);L(c.mode)?(c.Da=K.Oa.dir.node,c.Ea=K.Oa.dir.stream,c.Ca={}):32768===(c.mode&61440)?(c.Da=K.Oa.file.node,c.Ea=K.Oa.file.stream,c.Fa=0,c.Ca=null):40960===(c.mode&61440)?(c.Da=K.Oa.link.node,c.Ea=K.Oa.link.stream):8192===(c.mode&61440)&&(c.Da=K.Oa.zb.node,c.Ea=K.Oa.zb.stream);c.timestamp=Date.now();a&&(a.Ca[b]=c);return c},Vb:function(a){if(a.Ca&&a.Ca.subarray){for(var b=
[],c=0;c<a.Fa;++c)b.push(a.Ca[c]);return b}return a.Ca},te:function(a){return a.Ca?a.Ca.subarray?a.Ca.subarray(0,a.Fa):new Uint8Array(a.Ca):new Uint8Array},Ab:function(a,b){a.Ca&&a.Ca.subarray&&b>a.Ca.length&&(a.Ca=K.Vb(a),a.Fa=a.Ca.length);if(!a.Ca||a.Ca.subarray){var c=a.Ca?a.Ca.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.Ca,a.Ca=new Uint8Array(b),0<a.Fa&&a.Ca.set(c.subarray(0,a.Fa),0))}else for(!a.Ca&&0<b&&(a.Ca=[]);a.Ca.length<b;)a.Ca.push(0)},cc:function(a,
b){if(a.Fa!=b)if(0==b)a.Ca=null,a.Fa=0;else{if(!a.Ca||a.Ca.subarray){var c=a.Ca;a.Ca=new Uint8Array(new ArrayBuffer(b));c&&a.Ca.set(c.subarray(0,Math.min(b,a.Fa)))}else if(a.Ca||(a.Ca=[]),a.Ca.length>b)a.Ca.length=b;else for(;a.Ca.length<b;)a.Ca.push(0);a.Fa=b}},Da:{Na:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Fa:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;
b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Ra=4096;b.blocks=Math.ceil(b.size/b.Ra);return b},Ja:function(a,b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.cc(a,b.size)},lookup:function(){throw sb[J.Mb];},Za:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=tb(b,c)}catch(g){}if(d)for(var f in d.Ca)throw new I(J.ub);}delete a.parent.Ca[a.name];a.name=c;
b.Ca[c]=a;a.parent=b},unlink:function(a,b){delete a.Ca[b]},rmdir:function(a,b){var c=tb(a,b),d;for(d in c.Ca)throw new I(J.ub);delete a.Ca[b]},readdir:function(a){var b=[".",".."],c;for(c in a.Ca)a.Ca.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(J.Ka);return a.link}},Ea:{read:function(a,b,c,d,f){var g=a.node.Ca;if(f>=a.node.Fa)return 0;a=Math.min(a.node.Fa-f,d);assert(0<=a);
if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.Ca||a.Ca.subarray)){if(g)return a.Ca=b.subarray(c,c+d),a.Fa=d;if(0===a.Fa&&0===f)return a.Ca=new Uint8Array(b.subarray(c,c+d)),a.Fa=d;if(f+d<=a.Fa)return a.Ca.set(b.subarray(c,c+d),f),d}K.Ab(a,f+d);if(a.Ca.subarray&&b.subarray)a.Ca.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.Ca[f+g]=b[c+g];a.Fa=Math.max(a.Fa,f+
d);return d},Pa:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Fa);if(0>b)throw new I(J.Ka);return b},wb:function(a,b,c){K.Ab(a.node,b+c);a.node.Fa=Math.max(a.node.Fa,b+c)},eb:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new I(J.ib);c=a.node.Ca;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.Fa)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=D(d);if(!d)throw new I(J.tb);b.set(c,d)}else a=!1,d=c.byteOffset;
return{bc:d,jb:a}},fb:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new I(J.ib);if(f&2)return 0;K.Ea.write(a,b,0,d,c,!1);return 0}}},M={cb:!1,fc:function(){M.cb=!!process.platform.match(/^win/);var a=process.binding("constants");a.fs&&(a=a.fs);M.Bb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},xb:function(a){return Buffer.Ga?Buffer.from(a):new Buffer(a)},La:function(a){assert(da);return M.createNode(null,"/",M.Eb(a.nb.root),
0)},createNode:function(a,b,c){if(!L(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new I(J.Ka);a=rb(a,b,c);a.Da=M.Da;a.Ea=M.Ea;return a},Eb:function(a){try{var b=fs.lstatSync(a);M.cb&&(b.mode=b.mode|(b.mode&292)>>2)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}return b.mode},Ma:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.La.nb.root);b.reverse();return fb.apply(null,b)},Ub:function(a){a&=-2656257;var b=0,c;for(c in M.Bb)a&c&&(b|=M.Bb[c],a^=c);if(a)throw new I(J.Ka);
return b},Da:{Na:function(a){a=M.Ma(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}M.cb&&!b.Ra&&(b.Ra=4096);M.cb&&!b.blocks&&(b.blocks=(b.size+b.Ra-1)/b.Ra|0);return{dev:b.dev,ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Ra:b.Ra,blocks:b.blocks}},Ja:function(a,b){var c=M.Ma(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;
throw new I(J[d.code]);}},lookup:function(a,b){var c=H(M.Ma(a),b);c=M.Eb(c);return M.createNode(a,b,c)},Za:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.Ma(a);try{L(a.mode)?fs.mkdirSync(b,a.mode):fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new I(J[f.code]);}return a},rename:function(a,b,c){a=M.Ma(a);b=H(M.Ma(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},unlink:function(a,b){a=H(M.Ma(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;
throw new I(J[c.code]);}},rmdir:function(a,b){a=H(M.Ma(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}},readdir:function(a){a=M.Ma(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;throw new I(J[b.code]);}},symlink:function(a,b,c){a=H(M.Ma(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},readlink:function(a){var b=M.Ma(a);try{return b=fs.readlinkSync(b),b=ub.relative(ub.resolve(a.La.nb.root),b)}catch(c){if(!c.code)throw c;
throw new I(J[c.code]);}}},Ea:{open:function(a){var b=M.Ma(a.node);try{32768===(a.node.mode&61440)&&(a.ab=fs.openSync(b,M.Ub(a.flags)))}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}},close:function(a){try{32768===(a.node.mode&61440)&&a.ab&&fs.closeSync(a.ab)}catch(b){if(!b.code)throw b;throw new I(J[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.ab,M.xb(b.buffer),c,d,f)}catch(g){throw new I(J[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.ab,
M.xb(b.buffer),c,d,f)}catch(g){throw new I(J[g.code]);}},Pa:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.ab).size}catch(d){throw new I(J[d.code]);}if(0>b)throw new I(J.Ka);return b}}},vb=null,wb={},N=[],xb=1,O=null,yb=!0,P={},I=null,sb={};
function Q(a,b){a=gb("/",a);b=b||{};if(!a)return{path:"",node:null};var c={Cb:!0,pb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.pb)throw new I(40);a=bb(a.split("/").filter(function(a){return!!a}),!1);var f=vb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=tb(f,a[d]);c=H(c,a[d]);f.$a&&(!g||g&&b.Cb)&&(f=f.$a.root);if(!g||b.Ya)for(g=0;40960===(f.mode&61440);)if(f=zb(c),c=gb(db(c),f),f=Q(c,{pb:b.pb}).node,40<g++)throw new I(40);}return{path:c,node:f}}
function R(a){for(var b;;){if(a===a.parent)return a=a.La.Ib,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function Ab(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%O.length}function Bb(a){var b=Ab(a.parent.id,a.name);a.Wa=O[b];O[b]=a}function tb(a,b){var c;if(c=(c=Cb(a,"x"))?c:a.Da.lookup?0:13)throw new I(c,a);for(c=O[Ab(a.id,b)];c;c=c.Wa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.Da.lookup(a,b)}
function rb(a,b,c,d){Db||(Db=function(a,b,c,d){a||(a=this);this.parent=a;this.La=a.La;this.$a=null;this.id=xb++;this.name=b;this.mode=c;this.Da={};this.Ea={};this.rdev=d},Db.prototype={},Object.defineProperties(Db.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Yb:{get:function(){return L(this.mode)}},Xb:{get:function(){return 8192===
(this.mode&61440)}}}));a=new Db(a,b,c,d);Bb(a);return a}function L(a){return 16384===(a&61440)}var Eb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Fb(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function Cb(a,b){if(yb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}
function Gb(a,b){try{return tb(a,b),17}catch(c){}return Cb(a,"wx")}function Hb(a){var b=4096;for(a=a||0;a<=b;a++)if(!N[a])return a;throw new I(24);}function Ib(a,b){Jb||(Jb=function(){},Jb.prototype={},Object.defineProperties(Jb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Jb,d;for(d in a)c[d]=a[d];a=c;b=Hb(b);a.fd=b;return N[b]=a}var qb={open:function(a){a.Ea=wb[a.node.rdev].Ea;a.Ea.open&&a.Ea.open(a)},Pa:function(){throw new I(29);}};
function jb(a,b){wb[a]={Ea:b}}function Kb(a,b){var c="/"===b,d=!b;if(c&&vb)throw new I(16);if(!c&&!d){var f=Q(b,{Cb:!1});b=f.path;f=f.node;if(f.$a)throw new I(16);if(!L(f.mode))throw new I(20);}b={type:a,nb:{},Ib:b,ac:[]};a=a.La(b);a.La=b;b.root=a;c?vb=a:f&&(f.$a=b,f.La&&f.La.ac.push(b))}function Lb(a,b,c){var d=Q(a,{parent:!0}).node;a=eb(a);if(!a||"."===a||".."===a)throw new I(22);var f=Gb(d,a);if(f)throw new I(f);if(!d.Da.Za)throw new I(1);return d.Da.Za(d,a,b,c)}
function S(a,b){return Lb(a,(void 0!==b?b:511)&1023|16384,0)}function Mb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Lb(a,b|8192,c)}function Nb(a,b){if(!gb(a))throw new I(2);var c=Q(b,{parent:!0}).node;if(!c)throw new I(2);b=eb(b);var d=Gb(c,b);if(d)throw new I(d);if(!c.Da.symlink)throw new I(1);return c.Da.symlink(c,b,a)}
function Ob(a){var b=Q(a,{parent:!0}).node,c=eb(a),d=tb(b,c);a:{try{var f=tb(b,c)}catch(h){f=h.Ia;break a}var g=Cb(b,"wx");f=g?g:L(f.mode)?21:0}if(f)throw new I(f);if(!b.Da.unlink)throw new I(1);if(d.$a)throw new I(16);try{P.willDeletePath&&P.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.Da.unlink(b,c);b=Ab(d.parent.id,d.name);if(O[b]===d)O[b]=d.Wa;else for(b=O[b];b;){if(b.Wa===d){b.Wa=d.Wa;break}b=b.Wa}try{if(P.onDeletePath)P.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function zb(a){a=Q(a).node;if(!a)throw new I(2);if(!a.Da.readlink)throw new I(22);return gb(R(a.parent),a.Da.readlink(a))}function Pb(a,b){var c;"string"===typeof a?c=Q(a,{Ya:!0}).node:c=a;if(!c.Da.Ja)throw new I(1);c.Da.Ja(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Qb(a,b,c,d){if(""===a)throw new I(2);if("string"===typeof b){var f=Eb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=cb(a);try{g=Q(a,{Ya:!(b&131072)}).node}catch(l){}}f=!1;if(b&64)if(g){if(b&128)throw new I(17);}else g=Lb(a,c,0),f=!0;if(!g)throw new I(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!L(g.mode))throw new I(20);if(!f&&(c=g?40960===(g.mode&61440)?40:L(g.mode)&&
("r"!==Fb(b)||b&512)?21:Cb(g,Fb(b)):2))throw new I(c);if(b&512){c=g;var h;"string"===typeof c?h=Q(c,{Ya:!0}).node:h=c;if(!h.Da.Ja)throw new I(1);if(L(h.mode))throw new I(21);if(32768!==(h.mode&61440))throw new I(22);if(c=Cb(h,"w"))throw new I(c);h.Da.Ja(h,{size:0,timestamp:Date.now()})}b&=-641;d=Ib({node:g,path:R(g),flags:b,seekable:!0,position:0,Ea:g.Ea,lc:[],error:!1},d);d.Ea.open&&d.Ea.open(d);!e.logReadFiles||b&1||(Rb||(Rb={}),a in Rb||(Rb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{P.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),P.onOpenFile(a,g))}catch(l){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Sb(a){if(null===a.fd)throw new I(9);a.Sa&&(a.Sa=null);try{a.Ea.close&&a.Ea.close(a)}catch(b){throw b;}finally{N[a.fd]=null}a.fd=null}function Tb(a,b,c){if(null===a.fd)throw new I(9);if(!a.seekable||!a.Ea.Pa)throw new I(29);a.position=a.Ea.Pa(a,b,c);a.lc=[]}
function Ub(a,b,c,d,f,g){if(0>d||0>f)throw new I(22);if(null===a.fd)throw new I(9);if(0===(a.flags&2097155))throw new I(9);if(L(a.node.mode))throw new I(21);if(!a.Ea.write)throw new I(22);a.flags&1024&&Tb(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new I(29);b=a.Ea.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&P.onWriteToFile)P.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+path+"') threw an exception: "+l.message)}return b}
function Vb(){I||(I=function(a,b){this.node=b;this.ec=function(a){this.Ia=a};this.ec(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},I.prototype=Error(),I.prototype.constructor=I,[2].forEach(function(a){sb[a]=new I(a);sb[a].stack="<generic error, no stack>"}))}var Wb;function Xb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Yb(a,b,c,d){a=H("string"===typeof a?a:R(a),b);return S(a,Xb(c,d))}
function Zb(a,b){a="string"===typeof a?a:R(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=H(a,c);try{S(d)}catch(f){}a=d}}return d}function $b(a,b,c,d){a=H("string"===typeof a?a:R(a),b);c=Xb(c,d);return Lb(a,(void 0!==c?c:438)&4095|32768,0)}
function bc(a,b,c,d,f,g){a=b?H("string"===typeof a?a:R(a),b):a;d=Xb(d,f);f=Lb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Pb(f,d|146);a=Qb(f,"w");Ub(a,c,0,c.length,0,g);Sb(a);Pb(f,d)}return f}
function T(a,b,c,d){a=H("string"===typeof a?a:R(a),b);b=Xb(!!c,!!d);T.Hb||(T.Hb=64);var f=T.Hb++<<8|0;jb(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var m=c()}catch(A){throw new I(5);}if(void 0===m&&0===g)throw new I(11);if(null===m||void 0===m)break;g++;b[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(u){throw new I(5);}f&&(a.node.timestamp=
Date.now());return g}});return Mb(a,b,f)}function cc(a,b,c){a=H("string"===typeof a?a:R(a),b);return Nb(c,a)}
function dc(a){if(a.Xb||a.Yb||a.link||a.Ca)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.Ca=nb(e.read(a.url),!0),a.Fa=a.Ca.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||ab(5);return b}
function ec(a,b,c,d,f){function g(){this.mb=!1;this.bb=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Gb(a/this.chunkSize|0)[b]}};g.prototype.dc=function(a){this.Gb=a};g.prototype.yb=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.dc(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.bb[a]){var z=h.bb;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var m=new XMLHttpRequest;m.open("GET",c,!1);b!==g&&m.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(m.responseType="arraybuffer");
m.overrideMimeType&&m.overrideMimeType("text/plain; charset=x-user-defined");m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);d=void 0!==m.response?new Uint8Array(m.response||[]):nb(m.responseText||"",!0);z[a]=d}if("undefined"===typeof h.bb[a])throw Error("doXHR failed!");return h.bb[a]});if(a||!b)g=b=1,g=b=this.Gb(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Qb=b;this.Pb=
g;this.mb=!0};if("undefined"!==typeof XMLHttpRequest){if(!q)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.mb||this.yb();return this.Qb}},chunkSize:{get:function(){this.mb||this.yb();return this.Pb}}});var l=void 0}else l=c,h=void 0;var n=$b(a,b,d,f);h?n.Ca=h:l&&(n.Ca=null,n.url=l);Object.defineProperties(n,{Fa:{get:function(){return this.Ca.length}}});var r=
{};Object.keys(n.Ea).forEach(function(a){var b=n.Ea[a];r[a]=function(){if(!dc(n))throw new I(5);return b.apply(null,arguments)}});r.read=function(a,b,c,d,f){if(!dc(n))throw new I(5);a=a.node.Ca;if(f>=a.length)return 0;d=Math.min(a.length-f,d);assert(0<=d);if(a.slice)for(var z=0;z<d;z++)b[c+z]=a[f+z];else for(z=0;z<d;z++)b[c+z]=a.get(f+z);return d};n.Ea=r;return n}
function fc(a,b,c,d,f,g,h,l,n,r){function u(c){function z(c){r&&r();l||bc(a,b,c,d,f,n);g&&g();Ra(A)}var aa=!1;e.preloadPlugins.forEach(function(a){!aa&&a.canHandle(m)&&(a.handle(c,m,z,function(){h&&h();Ra(A)}),aa=!0)});aa||z(c)}(void 0).ue();var m=b?gb(H(a,b)):a,A="cp "+m;Qa(A);"string"==typeof c?(void 0).re(c,function(a){u(a)},h):u(c)}
var U={},Db,Jb,Rb,J={Ob:1,Mb:2,ee:3,Wc:4,sb:5,vb:6,mc:7,yd:8,rb:9,Cc:10,Lb:11,oe:11,tb:12,nc:13,Pc:14,Kd:15,Ac:16,Oc:17,pe:18,ib:19,Nb:20,Yc:21,Ka:22,td:23,ld:24,Ua:25,le:26,Qc:27,Gd:28,de:29,ae:30,md:31,Ud:32,Lc:33,Yd:34,Cd:42,Tc:43,Dc:44,$c:45,ad:46,bd:47,jd:48,me:49,wd:50,Zc:51,Ic:35,zd:37,tc:52,wc:53,qe:54,ud:55,xc:56,yc:57,Jc:35,zc:59,Id:60,xd:61,ie:62,Hd:63,Dd:64,Ed:65,$d:66,Ad:67,qc:68,fe:69,Ec:70,Vd:71,od:72,Mc:73,vc:74,Pd:76,uc:77,Zd:78,cd:79,dd:80,hd:81,gd:82,ed:83,Jd:38,ub:39,pd:36,kd:40,
Qd:95,Td:96,Hc:104,vd:105,rc:97,Xd:91,Nd:88,Fd:92,be:108,Gc:111,oc:98,Fc:103,sd:101,qd:100,je:110,Rc:112,Sc:113,Vc:115,sc:114,Kc:89,nd:90,Wd:93,ce:94,pc:99,rd:102,Xc:106,Ld:107,ke:109,ne:87,Nc:122,ge:116,Od:95,Bd:123,Uc:84,Rd:75,Bc:125,Md:131,Sd:130,he:86},hc={};
function ic(a,b){try{var c=Q(a,{Ya:!0}).node;if(!c)throw new I(2);if(!c.Da.Na)throw new I(1);var d=c.Da.Na(c)}catch(f){if(f&&f.node&&cb(a)!==cb(R(f.node)))return-J.Nb;throw f;}C[b>>2]=d.dev;C[b+4>>2]=0;C[b+8>>2]=d.ino;C[b+12>>2]=d.mode;C[b+16>>2]=d.nlink;C[b+20>>2]=d.uid;C[b+24>>2]=d.gid;C[b+28>>2]=d.rdev;C[b+32>>2]=0;C[b+36>>2]=d.size;C[b+40>>2]=4096;C[b+44>>2]=d.blocks;C[b+48>>2]=d.atime.getTime()/1E3|0;C[b+52>>2]=0;C[b+56>>2]=d.mtime.getTime()/1E3|0;C[b+60>>2]=0;C[b+64>>2]=d.ctime.getTime()/1E3|
0;C[b+68>>2]=0;C[b+72>>2]=d.ino;return 0}var V=0;function W(){V+=4;return C[V-4>>2]}function X(){var a=N[W()];if(!a)throw new I(J.rb);return a}function jc(a){if(0===a)return 0;a=F(a);if(!G.hasOwnProperty(a))return 0;jc.Ga&&Y(jc.Ga);a=G[a];var b=Ca(a)+1,c=D(b);c&&qa(a,w,c,b);jc.Ga=c;return jc.Ga}function kc(){kc.Ga||(kc.Ga=[]);kc.Ga.push(na());return kc.Ga.length-1}var lc={},mc=1;function nc(a,b){nc.Ga||(nc.Ga={});a in nc.Ga||(e.dynCall_v(b),nc.Ga[a]=1)}
function oc(a){return 0===a%4&&(0!==a%100||0===a%400)}function pc(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var qc=[31,29,31,30,31,30,31,31,30,31,30,31],rc=[31,28,31,30,31,30,31,31,30,31,30,31];function sc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(oc(a.getFullYear())?qc:rc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function tc(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function n(a){a=sc(new Date(a.Ha+1900,0,1),a.hb);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var r=C[d+40>>2];d={jc:C[d>>2],ic:C[d+4>>2],gb:C[d+8>>2],Ta:C[d+12>>2],Qa:C[d+16>>2],Ha:C[d+20>>2],Kb:C[d+24>>2],hb:C[d+28>>2],we:C[d+32>>2],hc:C[d+36>>2],
kc:r?F(r):""};c=F(c);r={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var u in r)c=c.replace(new RegExp(u,"g"),r[u]);var m="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),A="January February March April May June July August September October November December".split(" ");r={"%a":function(a){return m[a.Kb].substring(0,3)},"%A":function(a){return m[a.Kb]},"%b":function(a){return A[a.Qa].substring(0,
3)},"%B":function(a){return A[a.Qa]},"%C":function(a){return g((a.Ha+1900)/100|0,2)},"%d":function(a){return g(a.Ta,2)},"%e":function(a){return f(a.Ta,2," ")},"%g":function(a){return n(a).toString().substring(2)},"%G":function(a){return n(a)},"%H":function(a){return g(a.gb,2)},"%I":function(a){a=a.gb;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Ta+pc(oc(a.Ha+1900)?qc:rc,a.Qa-1),3)},"%m":function(a){return g(a.Qa+1,2)},"%M":function(a){return g(a.ic,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.gb&&12>a.gb?"AM":"PM"},"%S":function(a){return g(a.jc,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Ha+1900,a.Qa+1,a.Ta,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Ha+1900,0,1),c=0===b.getDay()?b:sc(b,7-b.getDay());a=new Date(a.Ha+1900,a.Qa,a.Ta);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(pc(oc(a.getFullYear())?qc:rc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.Ha+1900,0,4)),c=l(new Date(a.Ha+
1901,0,4)),d=sc(new Date(a.Ha+1900,0,1),a.hb);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Ha+1900?a.hb+32-b.getDate():a.hb+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Ha+1900,a.Qa+1,a.Ta,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Ha,0,1),c=1===b.getDay()?b:sc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Ha+1900,a.Qa,a.Ta);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(pc(oc(a.getFullYear())?qc:rc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":
"00"},"%y":function(a){return(a.Ha+1900).toString().substring(2)},"%Y":function(a){return a.Ha+1900},"%z":function(a){a=a.hc;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.kc},"%%":function(){return"%"}};for(u in r)0<=c.indexOf(u)&&(c=c.replace(new RegExp(u,"g"),r[u](d)));u=nb(c,!1);if(u.length>b)return 0;w.set(u,a);return u.length-1}Vb();O=Array(4096);Kb(K,"/");S("/tmp");S("/home");S("/home/web_user");
(function(){S("/dev");jb(259,{read:function(){return 0},write:function(a,b,f,g){return g}});Mb("/dev/null",259);ib(1280,ob);ib(1536,pb);Mb("/dev/tty",1280);Mb("/dev/tty1",1536);if("undefined"!==typeof crypto){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else da?b=function(){return require("crypto").randomBytes(1)[0]}:b=function(){v("random_device")};T("/dev","random",b);T("/dev","urandom",b);S("/dev/shm");S("/dev/shm/tmp")})();S("/proc");S("/proc/self");S("/proc/self/fd");
Kb({La:function(){var a=rb("/proc/self","fd",16895,73);a.Da={lookup:function(a,c){var b=N[+c];if(!b)throw new I(9);a={parent:null,La:{Ib:"fake"},Da:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");
Ia.unshift(function(){if(!e.noFSInit&&!Wb){assert(!Wb,"FS.init was previously called. If you want to initialize later with custom parameters, remove any earlier calls (note that one is automatically added to the generated code)");Wb=!0;Vb();e.stdin=e.stdin;e.stdout=e.stdout;e.stderr=e.stderr;e.stdin?T("/dev","stdin",e.stdin):Nb("/dev/tty","/dev/stdin");e.stdout?T("/dev","stdout",null,e.stdout):Nb("/dev/tty","/dev/stdout");e.stderr?T("/dev","stderr",null,e.stderr):Nb("/dev/tty1","/dev/stderr");var a=
Qb("/dev/stdin","r");assert(0===a.fd,"invalid handle for stdin ("+a.fd+")");a=Qb("/dev/stdout","w");assert(1===a.fd,"invalid handle for stdout ("+a.fd+")");a=Qb("/dev/stderr","w");assert(2===a.fd,"invalid handle for stderr ("+a.fd+")")}});Ja.push(function(){yb=!1});Ka.push(function(){Wb=!1;var a=e._fflush;a&&a(0);for(a=0;a<N.length;a++){var b=N[a];b&&Sb(b)}});e.FS_createFolder=Yb;e.FS_createPath=Zb;e.FS_createDataFile=bc;e.FS_createPreloadedFile=fc;e.FS_createLazyFile=ec;e.FS_createLink=cc;
e.FS_createDevice=T;e.FS_unlink=Ob;Ia.unshift(function(){});Ka.push(function(){});if(da){var fs=require("fs"),ub=require("path");M.fc()}function nb(a,b){var c=Array(Ca(a)+1);a=qa(a,c,0,c.length);b&&(c.length=a);return c}e.wasmTableSize=748;e.wasmMaxTableSize=748;
e.Rb={e:v,K:Fa,l:function(a,b,c,d){v("Assertion failed: "+F(a)+", at: "+[b?F(b):"unknown filename",c,d?F(d):"unknown function"])},z:$a,d:function(a){return D(a)},c:function(a){"uncaught_exception"in uc?uc.qb++:uc.qb=1;throw a+" - Exception catching is disabled, this exception cannot be caught. Compile with -s DISABLE_EXCEPTION_CATCHING=0 or DISABLE_EXCEPTION_CATCHING=2 to catch.";},s:function(){return!!uc.qb},n:function(){},r:function(){ab(1);return-1},m:ab,J:function(a,b){V=b;try{var c=X();W();var d=
W(),f=W(),g=W();Tb(c,d,g);C[f>>2]=c.position;c.Sa&&0===d&&0===g&&(c.Sa=null);return 0}catch(h){return"undefined"!==typeof U&&h instanceof I||v(h),-h.Ia}},I:function(a,b){V=b;try{var c=X(),d=W();a:{var f=W();for(b=a=0;b<f;b++){var g=C[d+(8*b+4)>>2],h=c,l=C[d+8*b>>2],n=g,r=void 0,u=w;if(0>n||0>r)throw new I(22);if(null===h.fd)throw new I(9);if(1===(h.flags&2097155))throw new I(9);if(L(h.node.mode))throw new I(21);if(!h.Ea.read)throw new I(22);var m="undefined"!==typeof r;if(!m)r=h.position;else if(!h.seekable)throw new I(29);
var A=h.Ea.read(h,u,l,n,r);m||(h.position+=A);var z=A;if(0>z){var mb=-1;break a}a+=z;if(z<g)break}mb=a}return mb}catch(aa){return"undefined"!==typeof U&&aa instanceof I||v(aa),-aa.Ia}},q:function(a,b){V=b;try{var c=X(),d=W();a:{var f=W();for(b=a=0;b<f;b++){var g=Ub(c,w,C[d+8*b>>2],C[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(l){return"undefined"!==typeof U&&l instanceof I||v(l),-l.Ia}},H:function(a,b){V=b;try{var c=W(),d=W(),f=W(),g=W(),h=W(),l=W();l<<=12;a=!1;if(-1===
h){var n=vc(16384,d);if(!n)return-J.tb;wc(n,0,d);a=!0}else{var r=N[h];if(!r)return-J.rb;b=x;if(1===(r.flags&2097155))throw new I(13);if(!r.Ea.eb)throw new I(19);var u=r.Ea.eb(r,b,c,d,l,f,g);n=u.bc;a=u.jb}hc[n]={$b:n,Zb:d,jb:a,fd:h,flags:g};return n}catch(m){return"undefined"!==typeof U&&m instanceof I||v(m),-m.Ia}},G:function(a,b){V=b;try{var c=F(W()),d=W();return ic(c,d)}catch(f){return"undefined"!==typeof U&&f instanceof I||v(f),-f.Ia}},F:function(a,b){V=b;try{var c=X(),d=W();return ic(c.path,d)}catch(f){return"undefined"!==
typeof U&&f instanceof I||v(f),-f.Ia}},E:function(a,b){V=b;try{var c=X(),d=W(),f=W();if(!c.Sa){var g=Q(c.path,{Ya:!0}).node;if(!g.Da.readdir)throw new I(20);var h=g.Da.readdir(g);c.Sa=h}for(a=0;0<c.Sa.length&&a+268<=f;){var l=c.Sa.pop();if("."===l[0]){var n=1;var r=4}else{var u=tb(c.node,l);n=u.id;r=8192===(u.mode&61440)?2:L(u.mode)?4:40960===(u.mode&61440)?10:8}C[d+a>>2]=n;C[d+a+4>>2]=c.position;ua[d+a+8>>1]=268;w[d+a+10>>0]=r;qa(l,x,d+a+11,256);a+=268}return a}catch(m){return"undefined"!==typeof U&&
m instanceof I||v(m),-m.Ia}},i:function(a,b){V=b;try{var c=X();switch(W()){case 0:var d=W();return 0>d?-J.Ka:Qb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;case 3:return c.flags;case 4:return d=W(),c.flags|=d,0;case 12:case 12:return d=W(),ua[d+0>>1]=2,0;case 13:case 14:case 13:case 14:return 0;case 16:case 8:return-J.Ka;case 9:return ab(J.Ka),-1;default:return-J.Ka}}catch(f){return"undefined"!==typeof U&&f instanceof I||v(f),-f.Ia}},p:function(a,b){V=b;try{var c=F(W()),d=W(),f=W();return Qb(c,
d,f).fd}catch(g){return"undefined"!==typeof U&&g instanceof I||v(g),-g.Ia}},o:function(a,b){V=b;try{var c=X(),d=W();switch(d){case 21509:case 21505:return c.tty?0:-J.Ua;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?0:-J.Ua;case 21519:if(!c.tty)return-J.Ua;var f=W();return C[f>>2]=0;case 21520:return c.tty?-J.Ka:-J.Ua;case 21531:a=f=W();if(!c.Ea.Wb)throw new I(25);return c.Ea.Wb(c,d,a);case 21523:return c.tty?0:-J.Ua;case 21524:return c.tty?0:-J.Ua;default:v("bad ioctl syscall "+
d)}}catch(g){return"undefined"!==typeof U&&g instanceof I||v(g),-g.Ia}},k:function(a,b){V=b;try{var c=X();Sb(c);return 0}catch(d){return"undefined"!==typeof U&&d instanceof I||v(d),-d.Ia}},D:function(a,b){V=b;try{var c=W(),d=W(),f=hc[c];if(!f)return 0;if(d===f.Zb){var g=N[f.fd],h=f.flags,l=new Uint8Array(x.subarray(c,c+d));g&&g.Ea.fb&&g.Ea.fb(g,l,0,d,h);hc[c]=null;f.jb&&Y(f.$b)}return 0}catch(n){return"undefined"!==typeof U&&n instanceof I||v(n),-n.Ia}},j:function(){},b:function(){e.abort()},C:function(){return E},
B:function(a,b,c){x.set(x.subarray(b,b+c),a)},A:function(){Fa()},h:jc,g:function(a){var b=kc.Ga[a];kc.Ga.splice(a,1);oa(b)},f:kc,y:function(){return 0},x:function(a){return lc[a]||0},w:function(a){if(0==a)return J.Ka;C[a>>2]=mc;lc[mc]=0;mc++;return 0},v:nc,u:function(a,b){if(!(a in lc))return J.Ka;lc[a]=b;return 0},t:function(a,b,c,d){return tc(a,b,c,d)},a:za};var xc=e.asm({},e.Rb,buffer);e.asm=xc;
var Ya=e.__GLOBAL__sub_I_Analysis_cpp=function(){return e.asm.L.apply(null,arguments)},uc=e.__ZSt18uncaught_exceptionv=function(){return e.asm.M.apply(null,arguments)},Za=e.___emscripten_environ_constructor=function(){return e.asm.N.apply(null,arguments)};e.___errno_location=function(){return e.asm.O.apply(null,arguments)};
var Y=e._free=function(){return e.asm.P.apply(null,arguments)},D=e._malloc=function(){return e.asm.Q.apply(null,arguments)},vc=e._memalign=function(){return e.asm.R.apply(null,arguments)},wc=e._memset=function(){return e.asm.S.apply(null,arguments)};e._voikkoAnalyzeWordCstr=function(){return e.asm.T.apply(null,arguments)};e._voikkoFreeCstr=function(){return e.asm.U.apply(null,arguments)};e._voikkoFreeCstrArray=function(){return e.asm.V.apply(null,arguments)};
e._voikkoFreeErrorMessageCstr=function(){return e.asm.W.apply(null,arguments)};e._voikkoFreeGrammarError=function(){return e.asm.X.apply(null,arguments)};e._voikkoGetGrammarErrorCode=function(){return e.asm.Y.apply(null,arguments)};e._voikkoGetGrammarErrorLength=function(){return e.asm.Z.apply(null,arguments)};e._voikkoGetGrammarErrorShortDescription=function(){return e.asm._.apply(null,arguments)};e._voikkoGetGrammarErrorStartPos=function(){return e.asm.$.apply(null,arguments)};
e._voikkoGetGrammarErrorSuggestions=function(){return e.asm.aa.apply(null,arguments)};e._voikkoGetVersion=function(){return e.asm.ba.apply(null,arguments)};e._voikkoHyphenateCstr=function(){return e.asm.ca.apply(null,arguments)};e._voikkoInit=function(){return e.asm.da.apply(null,arguments)};e._voikkoInsertHyphensCstr=function(){return e.asm.ea.apply(null,arguments)};e._voikkoNextGrammarErrorCstr=function(){return e.asm.fa.apply(null,arguments)};
e._voikkoNextSentenceStartCstr=function(){return e.asm.ga.apply(null,arguments)};e._voikkoNextTokenCstr=function(){return e.asm.ha.apply(null,arguments)};e._voikkoSetBooleanOption=function(){return e.asm.ia.apply(null,arguments)};e._voikkoSetIntegerOption=function(){return e.asm.ja.apply(null,arguments)};e._voikkoSpellCstr=function(){return e.asm.ka.apply(null,arguments)};e._voikkoSuggestCstr=function(){return e.asm.la.apply(null,arguments)};
e._voikkoTerminate=function(){return e.asm.ma.apply(null,arguments)};e._voikko_dict_description=function(){return e.asm.na.apply(null,arguments)};e._voikko_dict_language=function(){return e.asm.oa.apply(null,arguments)};e._voikko_dict_script=function(){return e.asm.pa.apply(null,arguments)};e._voikko_dict_variant=function(){return e.asm.qa.apply(null,arguments)};e._voikko_free_dicts=function(){return e.asm.ra.apply(null,arguments)};
e._voikko_free_mor_analysis=function(){return e.asm.sa.apply(null,arguments)};e._voikko_free_mor_analysis_value_cstr=function(){return e.asm.ta.apply(null,arguments)};e._voikko_list_dicts=function(){return e.asm.ua.apply(null,arguments)};e._voikko_mor_analysis_keys=function(){return e.asm.va.apply(null,arguments)};e._voikko_mor_analysis_value_cstr=function(){return e.asm.wa.apply(null,arguments)};
var pa=e.stackAlloc=function(){return e.asm.za.apply(null,arguments)},oa=e.stackRestore=function(){return e.asm.Aa.apply(null,arguments)},na=e.stackSave=function(){return e.asm.Ba.apply(null,arguments)};e.dynCall_v=function(){return e.asm.xa.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.ya.apply(null,arguments)};e.asm=xc;e.getMemory=xa;e.addRunDependency=Qa;e.removeRunDependency=Ra;e.FS_createFolder=Yb;e.FS_createPath=Zb;e.FS_createDataFile=bc;e.FS_createPreloadedFile=fc;
e.FS_createLazyFile=ec;e.FS_createLink=cc;e.FS_createDevice=T;e.FS_unlink=Ob;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function ia(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}ia.prototype=Error();ia.prototype.constructor=ia;Pa=function yc(){e.calledRun||zc();e.calledRun||(Pa=yc)};
function zc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!la)){ya||(ya=!0,Ga(Ia));Ga(Ja);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();La.unshift(a)}Ga(La)}}if(!(0<Na)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ma();Ga(Ha);0<Na||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},
1);a()},1)):a())}}e.run=zc;function v(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ja(a),k(a),a=JSON.stringify(a)):a="";la=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=v;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;zc();
var Ac=y("voikkoInit","number",["number","string","string"]),Bc=y("voikkoTerminate",null,["number"]),Cc=y("voikkoSetBooleanOption","number",["number","number","number"]),Dc=y("voikkoSetIntegerOption","number",["number","number","number"]),Ec=y("voikkoSpellCstr","number",["number","string"]),Fc=y("voikkoSuggestCstr","number",["number","string"]),Gc=y("voikkoHyphenateCstr","number",["number","string"]),Hc=y("voikkoInsertHyphensCstr","number",["number","string","string","number"]),Ic=y("voikkoFreeCstrArray",
null,["number"]),Jc=y("voikkoFreeCstr",null,["number"]),Kc=y("voikkoNextTokenCstr","number",["number","number","number","number"]),Lc=y("voikkoNextSentenceStartCstr","number",["number","number","number","number"]),Mc=y("voikkoNextGrammarErrorCstr","number",["number","string","number","number","number"]),Nc=y("voikkoGetGrammarErrorCode","number",["number"]),Oc=y("voikkoGetGrammarErrorStartPos","number",["number"]),Pc=y("voikkoGetGrammarErrorLength","number",["number"]),Qc=y("voikkoGetGrammarErrorSuggestions",
"number",["number"]),Rc=y("voikkoFreeGrammarError",null,["number"]),Sc=y("voikkoGetGrammarErrorShortDescription","number",["number","string"]),Tc=y("voikkoFreeErrorMessageCstr",null,["number"]),Uc=y("voikkoAnalyzeWordCstr","number",["number","string"]),Vc=y("voikko_free_mor_analysis",null,["number"]),Wc=y("voikko_mor_analysis_keys","number",["number"]),Xc=y("voikko_mor_analysis_value_cstr","number",["number","number"]),Yc=y("voikko_free_mor_analysis_value_cstr",null,["number"]);
function Z(a){return-1==a.indexOf("\x00")}e.onRuntimeInitialized=function(){if("onLoad"in e)e.onLoad(e)};
e.init=function(a,b){function c(){if(null==n)throw"Attempt to use Voikko instance after terminate() was called";}function d(a,b,c){var d=Nc(a),f=Oc(a),m=Pc(a),h=Qc(a),A=[];h&&g(h,A);a=Sc(a,c);c=F(a);Tc(a);return{errorCode:d,startPos:b+f,errorLen:m,suggestions:A,shortDescription:c}}function f(a,b){c();if(0==Cc(n,a,b?1:0))throw"Could not set boolean option "+a+" to value "+b+".";}function g(a,b){for(var c=B(a,"i32*");0!=c;)b.push(F(c)),a+=4,c=B(a,"i32*")}function h(a){var b=[],c=Ca(a),d=D(c+1);qa(a,
x,d,c+1);for(var f=0,g=0,m=D(4);0<c;){var h=Kc(n,d+f,c,m),l=B(m,"i32");h=r[h];l=a.substring(g,g+l);g+=l.length;var u=Ca(l);b.push({type:h,text:l});f+=u;c-=u}Y(m);Y(d);return b}var l=D(4),n=Ac(l,a,b);if(!n)throw a=B(l,"i32*"),a=F(a),Y(l),a;Y(l);var r=["NONE","WORD","PUNCTUATION","WHITESPACE","UNKNOWN"],u=["NONE","NO_START","PROBABLE","POSSIBLE"];return{terminate:function(){n&&(Bc(n),n=null)},spell:function(a){c();return Z(a)&&1==Ec(n,a)},suggest:function(a){c();var b=[];if(!Z(a))return b;a=Fc(n,a);
if(0==a)return b;g(a,b);Ic(a);return b},grammarErrors:function(a,b){c();var f=[];if(!Z(a))return f;var g=0;a=a.replace("\r","\n").split("\n");for(var h=0;h<a.length;h++){for(var m=a[h],l=f,A=m,r=g,u=b,Zc=Ca(A),ac=0;;){var lb=Mc(n,A,Zc,0,ac);if(!lb)break;l.push(d(lb,r,u));Rc(lb);ac++}g+=m.length+1}return f},analyze:function(a){c();var b=[];if(!Z(a))return b;a=Uc(n,a);if(!a)return b;for(var d=a,f=B(d,"i32*");0!=f;){for(var g={},h=Wc(f),m=B(h,"i32*");0!=m;){var l=F(m);m=Xc(f,m);g[l]=F(m);Yc(m);h+=4;
m=B(h,"i32*")}b.push(g);d+=4;f=B(d,"i32*")}Vc(a);return b},tokens:function(a){c();for(var b=[],d=0,f=a.indexOf("\x00");-1!=f;f=a.indexOf("\x00",f+1))b.push.apply(b,h(a.substring(d,f))),b.push({type:"UNKNOWN",text:"\x00"}),d=f+1;b.push.apply(b,h(a.substring(d)));return b},sentences:function(a){c();var b=[];if(!Z(a))return b.push({text:a,nextStartType:"NONE"}),b;var d=Ca(a),f=D(d+1),g=f;qa(a,x,f,d+1);for(var h=D(4);0<d;){var m=Lc(n,g,d,h),l=B(h,"i32"),r=a.substring(0,l);b.push({text:r,nextStartType:u[m]});
a=a.substring(l);m=Ca(r);g+=m;d-=m}Y(h);Y(f);return b},getHyphenationPattern:function(a){c();if(!Z(a)){for(var b="",d=0;d<a.length;d++)b+=" ";return b}a=Gc(n,a);b=F(a);Jc(a);return b},hyphenate:function(a,b,d){void 0===b&&(b="-");void 0===d&&(d=!0);c();if(!Z(a)||!Z(b))return a;a=Hc(n,a,b,d?1:0);b=F(a);Jc(a);return b},setIgnoreDot:function(a){f(0,a)},setIgnoreNumbers:function(a){f(1,a)},setIgnoreUppercase:function(a){f(3,a)},setAcceptFirstUppercase:function(a){f(6,a)},setAcceptAllUppercase:function(a){f(7,
a)},setIgnoreNonwords:function(a){f(10,a)},setAcceptExtraHyphens:function(a){f(11,a)},setAcceptMissingHyphens:function(a){f(12,a)},setAcceptTitlesInGc:function(a){f(13,a)},setAcceptUnfinishedParagraphsInGc:function(a){f(14,a)},setAcceptBulletedListsInGc:function(a){f(16,a)},setNoUglyHyphenation:function(a){f(4,a)},setHyphenateUnknownWords:function(a){f(15,a)},setMinHyphenatedWordLength:function(a){c();if(0==Dc(n,9,a))throw"Could not set integer option 9 to value "+a+".";},setSuggestionStrategy:function(a){if("TYPO"==
a)f(8,!1);else if("OCR"==a)f(8,!0);else throw"Unknown suggestion strategy "+a;}}};


  return Libvoikko;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Libvoikko;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Libvoikko; });
    else if (typeof exports === 'object')
      exports["Libvoikko"] = Libvoikko;
    