
var Libvoikko = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  return (
function(Libvoikko) {
  Libvoikko = Libvoikko || {};

var e;e||(e=typeof Libvoikko !== 'undefined' ? Libvoikko : {});e.hb||(e.hb=0,e.Nb=0);e.hb++;
(function(a){function b(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onprogress=function(c){var f=b;c.total&&(f=c.total);if(c.loaded){d.Da?e.Ra[a].loaded=c.loaded:(d.Da=!0,e.Ra||(e.Ra={}),e.Ra[a]={loaded:c.loaded,total:f});var m=f=c=0,g;for(g in e.Ra){var h=e.Ra[g];c+=h.total;f+=h.loaded;m++}c=Math.ceil(c*e.hb/m);e.setStatus&&e.setStatus("Downloading data... ("+f+"/"+c+")")}else!e.Ra&&e.setStatus&&e.setStatus("Downloading data...")};d.onerror=function(){throw Error("NetworkError for: "+
a);};d.onload=function(){if(200==d.status||304==d.status||206==d.status||0==d.status&&d.response)c(d.response);else throw Error(d.statusText+" : "+d.responseURL);};d.send(null)}function c(a){console.error("package error:",a)}function d(){function b(a,b,c){this.start=a;this.end=b;this.audio=c}function c(c){e.Nb++;if(!c)throw"Loading data file failed."+Error().stack;if(!(c instanceof ArrayBuffer))throw"bad input to processPackageData"+Error().stack;c=new Uint8Array(c);var d=e.getMemory(c.length);e.HEAPU8.set(c,
d);b.prototype.Mb=e.HEAPU8.subarray(d,d+c.length);c=a.files;for(d=0;d<c.length;++d)b.prototype.requests[c[d].filename].onload();e.removeRunDependency("datafile_js/libvoikko.data")}e.FS_createPath("/","5",!0,!0);e.FS_createPath("/5","mor-morpho",!0,!0);b.prototype={requests:{},open:function(a,b){this.name=b;this.requests[b]=this;e.addRunDependency("fp "+this.name)},onload:function(){this.finish(this.Mb.subarray(this.start,this.end))},finish:function(a){e.FS_createDataFile(this.name,null,a,!0,!0,!0);
e.removeRunDependency("fp "+this.name);this.requests[this.name]=null}};for(var d=a.files,f=0;f<d.length;++f)(new b(d[f].start,d[f].end,d[f].audio)).open("GET",d[f].filename);e.addRunDependency("datafile_js/libvoikko.data");e.Db||(e.Db={});e.Db["js/libvoikko.data"]={me:!1};l?(c(l),l=null):h=c}if("object"===typeof window)window.encodeURIComponent(window.location.pathname.toString().substring(0,window.location.pathname.toString().lastIndexOf("/"))+"/");else if("undefined"!==typeof location)encodeURIComponent(location.pathname.toString().substring(0,
location.pathname.toString().lastIndexOf("/"))+"/");else throw"using preloaded data can only be done on a web page or in a web worker";"function"!==typeof e.locateFilePackage||e.locateFile||(e.locateFile=e.locateFilePackage,k("warning: you defined Module.locateFilePackage, that has been renamed to Module.locateFile (using your locateFilePackage for now)"));var f=e.locateFile?e.locateFile("libvoikko.data",""):"libvoikko.data",g=a.qe,h=null,l=e.getPreloadedPackage?e.getPreloadedPackage(f,g):null;l||
b(f,g,function(a){h?(h(a),h=null):l=a},c);e.calledRun?d():(e.preRun||(e.preRun=[]),e.preRun.push(d))})({files:[{start:0,audio:0,end:11360,filename:"/5/mor-morpho/autocorr.vfst"},{start:11360,audio:0,end:4712680,filename:"/5/mor-morpho/mor.vfst"},{start:4712680,audio:0,end:4713245,filename:"/5/mor-morpho/index.txt"}],remote_package_size:4713245,package_uuid:"3530180b-5d39-4b78-84e1-cc71b19b6fb1"});var aa={},n;for(n in e)e.hasOwnProperty(n)&&(aa[n]=e[n]);e.arguments=[];e.thisProgram="./this.program";
e.quit=function(a,b){throw b;};e.preRun=[];e.postRun=[];var ba=!1,q=!1,r=!1,ca=!1;ba="object"===typeof window;q="function"===typeof importScripts;r="object"===typeof process&&"function"===typeof require&&!ba&&!q;ca=!ba&&!r&&!q;var u="";
if(r){u=__dirname+"/";var da,ea;e.read=function(a,b){da||(da=require("fs"));ea||(ea=require("path"));a=ea.normalize(a);a=da.readFileSync(a);return b?a:a.toString()};e.readBinary=function(a){a=e.read(a,!0);a.buffer||(a=new Uint8Array(a));assert(a.buffer);return a};1<process.argv.length&&(e.thisProgram=process.argv[1].replace(/\\/g,"/"));e.arguments=process.argv.slice(2);process.on("uncaughtException",function(a){if(!(a instanceof fa))throw a;});process.on("unhandledRejection",w);e.quit=function(a){process.exit(a)};
e.inspect=function(){return"[Emscripten Module object]"}}else if(ca)"undefined"!=typeof read&&(e.read=function(a){return read(a)}),e.readBinary=function(a){if("function"===typeof readbuffer)return new Uint8Array(readbuffer(a));a=read(a,"binary");assert("object"===typeof a);return a},"undefined"!=typeof scriptArgs?e.arguments=scriptArgs:"undefined"!=typeof arguments&&(e.arguments=arguments),"function"===typeof quit&&(e.quit=function(a){quit(a)});else if(ba||q)q?u=self.location.href:document.currentScript&&
(u=document.currentScript.src),_scriptDir&&(u=_scriptDir),0!==u.indexOf("blob:")?u=u.substr(0,u.lastIndexOf("/")+1):u="",e.read=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},q&&(e.readBinary=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)}),e.readAsync=function(a,b,c){var d=new XMLHttpRequest;d.open("GET",a,!0);d.responseType="arraybuffer";d.onload=function(){200==d.status||
0==d.status&&d.response?b(d.response):c()};d.onerror=c;d.send(null)},e.setWindowTitle=function(a){document.title=a};var ha=e.print||("undefined"!==typeof console?console.log.bind(console):"undefined"!==typeof print?print:null),k=e.printErr||("undefined"!==typeof printErr?printErr:"undefined"!==typeof console&&console.warn.bind(console)||ha);for(n in aa)aa.hasOwnProperty(n)&&(e[n]=aa[n]);aa=void 0;var ia={"f64-rem":function(a,b){return a%b},"debugger":function(){debugger}};
"object"!==typeof WebAssembly&&k("no native wasm support detected");function x(a,b){b=b||"i8";"*"===b.charAt(b.length-1)&&(b="i32");switch(b){case "i1":return y[a>>0];case "i8":return y[a>>0];case "i16":return ja[a>>1];case "i32":return A[a>>2];case "i64":return A[a>>2];case "float":return ka[a>>2];case "double":return la[a>>3];default:w("invalid type for getValue: "+b)}return null}var ma,na=!1;function assert(a,b){a||w("Assertion failed: "+b)}
function oa(a){var b=e["_"+a];assert(b,"Cannot call unknown function "+a+", make sure it is exported");return b}
function pa(a,b,c,d){var f={string:function(a){var b=0;if(null!==a&&void 0!==a&&0!==a){var c=(a.length<<2)+1;b=qa(c);ra(a,B,b,c)}return b},array:function(a){var b=qa(a.length);y.set(a,b);return b}},g=oa(a),h=[];a=0;if(d)for(var l=0;l<d.length;l++){var p=f[c[l]];p?(0===a&&(a=sa()),h[l]=p(d[l])):h[l]=d[l]}c=g.apply(null,h);c=function(a){return"string"===b?C(a):"boolean"===b?!!a:a}(c);0!==a&&ta(a);return c}
function E(a,b,c){c=c||[];var d=c.every(function(a){return"number"===a});return"string"!==b&&d?oa(a):function(){return pa(a,b,c,arguments)}}function ua(a){if(va)var b=F(a);else b=A[wa>>2],a=b+a+15&-16,a<=xa()?A[wa>>2]=a:b=0;return b}var ya="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function za(a,b,c){var d=b+c;for(c=b;a[c]&&!(c>=d);)++c;if(16<c-b&&a.subarray&&ya)return ya.decode(a.subarray(b,c));for(d="";b<c;){var f=a[b++];if(f&128){var g=a[b++]&63;if(192==(f&224))d+=String.fromCharCode((f&31)<<6|g);else{var h=a[b++]&63;f=224==(f&240)?(f&15)<<12|g<<6|h:(f&7)<<18|g<<12|h<<6|a[b++]&63;65536>f?d+=String.fromCharCode(f):(f-=65536,d+=String.fromCharCode(55296|f>>10,56320|f&1023))}}else d+=String.fromCharCode(f)}return d}function C(a){return a?za(B,a,void 0):""}
function ra(a,b,c,d){if(!(0<d))return 0;var f=c;d=c+d-1;for(var g=0;g<a.length;++g){var h=a.charCodeAt(g);if(55296<=h&&57343>=h){var l=a.charCodeAt(++g);h=65536+((h&1023)<<10)|l&1023}if(127>=h){if(c>=d)break;b[c++]=h}else{if(2047>=h){if(c+1>=d)break;b[c++]=192|h>>6}else{if(65535>=h){if(c+2>=d)break;b[c++]=224|h>>12}else{if(c+3>=d)break;b[c++]=240|h>>18;b[c++]=128|h>>12&63}b[c++]=128|h>>6&63}b[c++]=128|h&63}}b[c]=0;return c-f}
function Aa(a){for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&(d=65536+((d&1023)<<10)|a.charCodeAt(++c)&1023);127>=d?++b:b=2047>=d?b+2:65535>=d?b+3:b+4}return b}"undefined"!==typeof TextDecoder&&new TextDecoder("utf-16le");var buffer,y,B,ja,A,ka,la,wa=37808,Ba=e.TOTAL_MEMORY||16777216;5242880>Ba&&k("TOTAL_MEMORY should be larger than TOTAL_STACK, was "+Ba+"! (TOTAL_STACK=5242880)");
e.buffer?buffer=e.buffer:"object"===typeof WebAssembly&&"function"===typeof WebAssembly.Memory?(ma=new WebAssembly.Memory({initial:Ba/65536,maximum:Ba/65536}),buffer=ma.buffer):buffer=new ArrayBuffer(Ba);e.HEAP8=y=new Int8Array(buffer);e.HEAP16=ja=new Int16Array(buffer);e.HEAP32=A=new Int32Array(buffer);e.HEAPU8=B=new Uint8Array(buffer);e.HEAPU16=new Uint16Array(buffer);e.HEAPU32=new Uint32Array(buffer);e.HEAPF32=ka=new Float32Array(buffer);e.HEAPF64=la=new Float64Array(buffer);A[wa>>2]=5280944;
function Ca(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b();else{var c=b.Pb;"number"===typeof c?void 0===b.gb?e.dynCall_v(c):e.dynCall_vi(c,b.gb):c(void 0===b.gb?null:b.gb)}}}var Da=[],Ea=[],Fa=[],Ga=[],va=!1;function Ha(){var a=e.preRun.shift();Da.unshift(a)}var Ia=0,Ja=null,Ka=null;function La(){Ia++;e.monitorRunDependencies&&e.monitorRunDependencies(Ia)}
function Ma(){Ia--;e.monitorRunDependencies&&e.monitorRunDependencies(Ia);if(0==Ia&&(null!==Ja&&(clearInterval(Ja),Ja=null),Ka)){var a=Ka;Ka=null;a()}}e.preloadedImages={};e.preloadedAudios={};function Na(){var a=Oa;return String.prototype.startsWith?a.startsWith("data:application/octet-stream;base64,"):0===a.indexOf("data:application/octet-stream;base64,")}var Oa="libvoikko.wasm";if(!Na()){var Pa=Oa;Oa=e.locateFile?e.locateFile(Pa,u):u+Pa}
function Qa(){try{if(e.wasmBinary)return new Uint8Array(e.wasmBinary);if(e.readBinary)return e.readBinary(Oa);throw"both async and sync fetching of the wasm failed";}catch(a){w(a)}}function Ra(){return e.wasmBinary||!ba&&!q||"function"!==typeof fetch?new Promise(function(a){a(Qa())}):fetch(Oa,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+Oa+"'";return a.arrayBuffer()}).catch(function(){return Qa()})}
function Sa(a){function b(a){e.asm=a.exports;Ma("wasm-instantiate")}function c(a){b(a.instance)}function d(a){Ra().then(function(a){return WebAssembly.instantiate(a,f)}).then(a,function(a){k("failed to asynchronously prepare wasm: "+a);w(a)})}var f={env:a,global:{NaN:NaN,Infinity:Infinity},"global.Math":Math,asm2wasm:ia};La("wasm-instantiate");if(e.instantiateWasm)try{return e.instantiateWasm(f,b)}catch(g){return k("Module.instantiateWasm callback failed with error: "+g),!1}e.wasmBinary||"function"!==
typeof WebAssembly.instantiateStreaming||Na()||"function"!==typeof fetch?d(c):WebAssembly.instantiateStreaming(fetch(Oa,{credentials:"same-origin"}),f).then(c,function(a){k("wasm streaming compile failed: "+a);k("falling back to ArrayBuffer instantiation");d(c)});return{}}e.asm=function(a,b){b.memory=ma;b.table=new WebAssembly.Table({initial:748,maximum:748,element:"anyfunc"});b.__memory_base=1024;b.__table_base=0;return Sa(b)};Ea.push({Pb:function(){Ta()}});var G={};
function Ua(a){if(Ua.Da){var b=A[a>>2];var c=A[b>>2]}else Ua.Da=!0,G.USER=G.LOGNAME="web_user",G.PATH="/",G.PWD="/",G.HOME="/home/web_user",G.LANG="C.UTF-8",G._=e.thisProgram,c=ua(1024),b=ua(256),A[b>>2]=c,A[a>>2]=b;a=[];var d=0,f;for(f in G)if("string"===typeof G[f]){var g=f+"="+G[f];a.push(g);d+=g.length}if(1024<d)throw Error("Environment size exceeded TOTAL_ENV_SIZE!");for(f=0;f<a.length;f++){d=g=a[f];for(var h=c,l=0;l<d.length;++l)y[h++>>0]=d.charCodeAt(l);y[h>>0]=0;A[b+4*f>>2]=c;c+=g.length+
1}A[b+4*a.length>>2]=0}function Va(a){e.___errno_location&&(A[e.___errno_location()>>2]=a);return a}function Wa(a,b){for(var c=0,d=a.length-1;0<=d;d--){var f=a[d];"."===f?a.splice(d,1):".."===f?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a}function Xa(a){var b="/"===a.charAt(0),c="/"===a.substr(-1);(a=Wa(a.split("/").filter(function(a){return!!a}),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a}
function Ya(a){var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);a=b[0];b=b[1];if(!a&&!b)return".";b&&(b=b.substr(0,b.length-1));return a+b}function Za(a){if("/"===a)return"/";var b=a.lastIndexOf("/");return-1===b?a:a.substr(b+1)}function $a(){var a=Array.prototype.slice.call(arguments,0);return Xa(a.join("/"))}function H(a,b){return Xa(a+"/"+b)}
function ab(){for(var a="",b=!1,c=arguments.length-1;-1<=c&&!b;c--){b=0<=c?arguments[c]:"/";if("string"!==typeof b)throw new TypeError("Arguments to path.resolve must be strings");if(!b)return"";a=b+"/"+a;b="/"===b.charAt(0)}a=Wa(a.split("/").filter(function(a){return!!a}),!b).join("/");return(b?"/":"")+a||"."}var bb=[];function cb(a,b){bb[a]={input:[],output:[],Ta:b};db(a,gb)}
var gb={open:function(a){var b=bb[a.node.rdev];if(!b)throw new I(J.eb);a.tty=b;a.seekable=!1},close:function(a){a.tty.Ta.flush(a.tty)},flush:function(a){a.tty.Ta.flush(a.tty)},read:function(a,b,c,d){if(!a.tty||!a.tty.Ta.zb)throw new I(J.qb);for(var f=0,g=0;g<d;g++){try{var h=a.tty.Ta.zb(a.tty)}catch(l){throw new I(J.nb);}if(void 0===h&&0===f)throw new I(J.Gb);if(null===h||void 0===h)break;f++;b[c+g]=h}f&&(a.node.timestamp=Date.now());return f},write:function(a,b,c,d){if(!a.tty||!a.tty.Ta.kb)throw new I(J.qb);
try{for(var f=0;f<d;f++)a.tty.Ta.kb(a.tty,b[c+f])}catch(g){throw new I(J.nb);}d&&(a.node.timestamp=Date.now());return f}},ib={zb:function(a){if(!a.input.length){var b=null;if(r){var c=new Buffer(256),d=0,f=process.stdin.fd;if("win32"!=process.platform){var g=!1;try{f=fs.openSync("/dev/stdin","r"),g=!0}catch(h){}}try{d=fs.readSync(f,c,0,256,null)}catch(h){if(-1!=h.toString().indexOf("EOF"))d=0;else throw h;}g&&fs.closeSync(f);0<d?b=c.slice(0,d).toString("utf-8"):b=null}else"undefined"!=typeof window&&
"function"==typeof window.prompt?(b=window.prompt("Input: "),null!==b&&(b+="\n")):"function"==typeof readline&&(b=readline(),null!==b&&(b+="\n"));if(!b)return null;a.input=hb(b,!0)}return a.input.shift()},kb:function(a,b){null===b||10===b?(ha(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<a.output.length&&(ha(za(a.output,0)),a.output=[])}},jb={kb:function(a,b){null===b||10===b?(k(za(a.output,0)),a.output=[]):0!=b&&a.output.push(b)},flush:function(a){a.output&&0<
a.output.length&&(k(za(a.output,0)),a.output=[])}},K={Ka:null,Ga:function(){return K.createNode(null,"/",16895,0)},createNode:function(a,b,c,d){if(24576===(c&61440)||4096===(c&61440))throw new I(J.Jb);K.Ka||(K.Ka={dir:{node:{Ia:K.za.Ia,Fa:K.za.Fa,lookup:K.za.lookup,Va:K.za.Va,rename:K.za.rename,unlink:K.za.unlink,rmdir:K.za.rmdir,readdir:K.za.readdir,symlink:K.za.symlink},stream:{La:K.Aa.La}},file:{node:{Ia:K.za.Ia,Fa:K.za.Fa},stream:{La:K.Aa.La,read:K.Aa.read,write:K.Aa.write,rb:K.Aa.rb,$a:K.Aa.$a,
ab:K.Aa.ab}},link:{node:{Ia:K.za.Ia,Fa:K.za.Fa,readlink:K.za.readlink},stream:{}},ub:{node:{Ia:K.za.Ia,Fa:K.za.Fa},stream:kb}});c=lb(a,b,c,d);L(c.mode)?(c.za=K.Ka.dir.node,c.Aa=K.Ka.dir.stream,c.ya={}):32768===(c.mode&61440)?(c.za=K.Ka.file.node,c.Aa=K.Ka.file.stream,c.Ba=0,c.ya=null):40960===(c.mode&61440)?(c.za=K.Ka.link.node,c.Aa=K.Ka.link.stream):8192===(c.mode&61440)&&(c.za=K.Ka.ub.node,c.Aa=K.Ka.ub.stream);c.timestamp=Date.now();a&&(a.ya[b]=c);return c},ne:function(a){if(a.ya&&a.ya.subarray){for(var b=
[],c=0;c<a.Ba;++c)b.push(a.ya[c]);return b}return a.ya},oe:function(a){return a.ya?a.ya.subarray?a.ya.subarray(0,a.Ba):new Uint8Array(a.ya):new Uint8Array},vb:function(a,b){var c=a.ya?a.ya.length:0;c>=b||(b=Math.max(b,c*(1048576>c?2:1.125)|0),0!=c&&(b=Math.max(b,256)),c=a.ya,a.ya=new Uint8Array(b),0<a.Ba&&a.ya.set(c.subarray(0,a.Ba),0))},Xb:function(a,b){if(a.Ba!=b)if(0==b)a.ya=null,a.Ba=0;else{if(!a.ya||a.ya.subarray){var c=a.ya;a.ya=new Uint8Array(new ArrayBuffer(b));c&&a.ya.set(c.subarray(0,Math.min(b,
a.Ba)))}else if(a.ya||(a.ya=[]),a.ya.length>b)a.ya.length=b;else for(;a.ya.length<b;)a.ya.push(0);a.Ba=b}},za:{Ia:function(a){var b={};b.dev=8192===(a.mode&61440)?a.id:1;b.ino=a.id;b.mode=a.mode;b.nlink=1;b.uid=0;b.gid=0;b.rdev=a.rdev;L(a.mode)?b.size=4096:32768===(a.mode&61440)?b.size=a.Ba:40960===(a.mode&61440)?b.size=a.link.length:b.size=0;b.atime=new Date(a.timestamp);b.mtime=new Date(a.timestamp);b.ctime=new Date(a.timestamp);b.Na=4096;b.blocks=Math.ceil(b.size/b.Na);return b},Fa:function(a,
b){void 0!==b.mode&&(a.mode=b.mode);void 0!==b.timestamp&&(a.timestamp=b.timestamp);void 0!==b.size&&K.Xb(a,b.size)},lookup:function(){throw mb[J.Hb];},Va:function(a,b,c,d){return K.createNode(a,b,c,d)},rename:function(a,b,c){if(L(a.mode)){try{var d=nb(b,c)}catch(g){}if(d)for(var f in d.ya)throw new I(J.pb);}delete a.parent.ya[a.name];a.name=c;b.ya[c]=a;a.parent=b},unlink:function(a,b){delete a.ya[b]},rmdir:function(a,b){var c=nb(a,b),d;for(d in c.ya)throw new I(J.pb);delete a.ya[b]},readdir:function(a){var b=
[".",".."],c;for(c in a.ya)a.ya.hasOwnProperty(c)&&b.push(c);return b},symlink:function(a,b,c){a=K.createNode(a,b,41471,0);a.link=c;return a},readlink:function(a){if(40960!==(a.mode&61440))throw new I(J.Ja);return a.link}},Aa:{read:function(a,b,c,d,f){var g=a.node.ya;if(f>=a.node.Ba)return 0;a=Math.min(a.node.Ba-f,d);if(8<a&&g.subarray)b.set(g.subarray(f,f+a),c);else for(d=0;d<a;d++)b[c+d]=g[f+d];return a},write:function(a,b,c,d,f,g){if(!d)return 0;a=a.node;a.timestamp=Date.now();if(b.subarray&&(!a.ya||
a.ya.subarray)){if(g)return a.ya=b.subarray(c,c+d),a.Ba=d;if(0===a.Ba&&0===f)return a.ya=new Uint8Array(b.subarray(c,c+d)),a.Ba=d;if(f+d<=a.Ba)return a.ya.set(b.subarray(c,c+d),f),d}K.vb(a,f+d);if(a.ya.subarray&&b.subarray)a.ya.set(b.subarray(c,c+d),f);else for(g=0;g<d;g++)a.ya[f+g]=b[c+g];a.Ba=Math.max(a.Ba,f+d);return d},La:function(a,b,c){1===c?b+=a.position:2===c&&32768===(a.node.mode&61440)&&(b+=a.node.Ba);if(0>b)throw new I(J.Ja);return b},rb:function(a,b,c){K.vb(a.node,b+c);a.node.Ba=Math.max(a.node.Ba,
b+c)},$a:function(a,b,c,d,f,g,h){if(32768!==(a.node.mode&61440))throw new I(J.eb);c=a.node.ya;if(h&2||c.buffer!==b&&c.buffer!==b.buffer){if(0<f||f+d<a.node.Ba)c.subarray?c=c.subarray(f,f+d):c=Array.prototype.slice.call(c,f,f+d);a=!0;d=F(d);if(!d)throw new I(J.ob);b.set(c,d)}else a=!1,d=c.byteOffset;return{Wb:d,fb:a}},ab:function(a,b,c,d,f){if(32768!==(a.node.mode&61440))throw new I(J.eb);if(f&2)return 0;K.Aa.write(a,b,0,d,c,!1);return 0}}},M={Za:!1,$b:function(){M.Za=!!process.platform.match(/^win/);
var a=process.binding("constants");a.fs&&(a=a.fs);M.wb={1024:a.O_APPEND,64:a.O_CREAT,128:a.O_EXCL,0:a.O_RDONLY,2:a.O_RDWR,4096:a.O_SYNC,512:a.O_TRUNC,1:a.O_WRONLY}},sb:function(a){return Buffer.Da?Buffer.from(a):new Buffer(a)},Ga:function(a){assert(r);return M.createNode(null,"/",M.yb(a.jb.root),0)},createNode:function(a,b,c){if(!L(c)&&32768!==(c&61440)&&40960!==(c&61440))throw new I(J.Ja);a=lb(a,b,c);a.za=M.za;a.Aa=M.Aa;return a},yb:function(a){try{var b=fs.lstatSync(a);M.Za&&(b.mode=b.mode|(b.mode&
292)>>2)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}return b.mode},Ha:function(a){for(var b=[];a.parent!==a;)b.push(a.name),a=a.parent;b.push(a.Ga.jb.root);b.reverse();return $a.apply(null,b)},Ob:function(a){a&=-2656257;var b=0,c;for(c in M.wb)a&c&&(b|=M.wb[c],a^=c);if(a)throw new I(J.Ja);return b},za:{Ia:function(a){a=M.Ha(a);try{var b=fs.lstatSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}M.Za&&!b.Na&&(b.Na=4096);M.Za&&!b.blocks&&(b.blocks=(b.size+b.Na-1)/b.Na|0);return{dev:b.dev,
ino:b.ino,mode:b.mode,nlink:b.nlink,uid:b.uid,gid:b.gid,rdev:b.rdev,size:b.size,atime:b.atime,mtime:b.mtime,ctime:b.ctime,Na:b.Na,blocks:b.blocks}},Fa:function(a,b){var c=M.Ha(a);try{void 0!==b.mode&&(fs.chmodSync(c,b.mode),a.mode=b.mode),void 0!==b.size&&fs.truncateSync(c,b.size)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},lookup:function(a,b){var c=H(M.Ha(a),b);c=M.yb(c);return M.createNode(a,b,c)},Va:function(a,b,c,d){a=M.createNode(a,b,c,d);b=M.Ha(a);try{L(a.mode)?fs.mkdirSync(b,a.mode):
fs.writeFileSync(b,"",{mode:a.mode})}catch(f){if(!f.code)throw f;throw new I(J[f.code]);}return a},rename:function(a,b,c){a=M.Ha(a);b=H(M.Ha(b),c);try{fs.renameSync(a,b)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},unlink:function(a,b){a=H(M.Ha(a),b);try{fs.unlinkSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}},rmdir:function(a,b){a=H(M.Ha(a),b);try{fs.rmdirSync(a)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}},readdir:function(a){a=M.Ha(a);try{return fs.readdirSync(a)}catch(b){if(!b.code)throw b;
throw new I(J[b.code]);}},symlink:function(a,b,c){a=H(M.Ha(a),b);try{fs.symlinkSync(c,a)}catch(d){if(!d.code)throw d;throw new I(J[d.code]);}},readlink:function(a){var b=M.Ha(a);try{return b=fs.readlinkSync(b),b=ob.relative(ob.resolve(a.Ga.jb.root),b)}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}}},Aa:{open:function(a){var b=M.Ha(a.node);try{32768===(a.node.mode&61440)&&(a.Xa=fs.openSync(b,M.Ob(a.flags)))}catch(c){if(!c.code)throw c;throw new I(J[c.code]);}},close:function(a){try{32768===(a.node.mode&
61440)&&a.Xa&&fs.closeSync(a.Xa)}catch(b){if(!b.code)throw b;throw new I(J[b.code]);}},read:function(a,b,c,d,f){if(0===d)return 0;try{return fs.readSync(a.Xa,M.sb(b.buffer),c,d,f)}catch(g){throw new I(J[g.code]);}},write:function(a,b,c,d,f){try{return fs.writeSync(a.Xa,M.sb(b.buffer),c,d,f)}catch(g){throw new I(J[g.code]);}},La:function(a,b,c){if(1===c)b+=a.position;else if(2===c&&32768===(a.node.mode&61440))try{b+=fs.fstatSync(a.Xa).size}catch(d){throw new I(J[d.code]);}if(0>b)throw new I(J.Ja);
return b}}},pb=null,qb={},rb=[],sb=1,N=null,tb=!0,O={},I=null,mb={};
function P(a,b){a=ab("/",a);b=b||{};if(!a)return{path:"",node:null};var c={xb:!0,lb:0},d;for(d in c)void 0===b[d]&&(b[d]=c[d]);if(8<b.lb)throw new I(40);a=Wa(a.split("/").filter(function(a){return!!a}),!1);var f=pb;c="/";for(d=0;d<a.length;d++){var g=d===a.length-1;if(g&&b.parent)break;f=nb(f,a[d]);c=H(c,a[d]);f.Wa&&(!g||g&&b.xb)&&(f=f.Wa.root);if(!g||b.Ua)for(g=0;40960===(f.mode&61440);)if(f=ub(c),c=ab(Ya(c),f),f=P(c,{lb:b.lb}).node,40<g++)throw new I(40);}return{path:c,node:f}}
function Q(a){for(var b;;){if(a===a.parent)return a=a.Ga.Cb,b?"/"!==a[a.length-1]?a+"/"+b:a+b:a;b=b?a.name+"/"+b:a.name;a=a.parent}}function vb(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%N.length}function wb(a){var b=vb(a.parent.id,a.name);a.Sa=N[b];N[b]=a}function nb(a,b){var c;if(c=(c=xb(a,"x"))?c:a.za.lookup?0:13)throw new I(c,a);for(c=N[vb(a.id,b)];c;c=c.Sa){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return a.za.lookup(a,b)}
function lb(a,b,c,d){yb||(yb=function(a,b,c,d){a||(a=this);this.parent=a;this.Ga=a.Ga;this.Wa=null;this.id=sb++;this.name=b;this.mode=c;this.za={};this.Aa={};this.rdev=d},yb.prototype={},Object.defineProperties(yb.prototype,{read:{get:function(){return 365===(this.mode&365)},set:function(a){a?this.mode|=365:this.mode&=-366}},write:{get:function(){return 146===(this.mode&146)},set:function(a){a?this.mode|=146:this.mode&=-147}},Sb:{get:function(){return L(this.mode)}},Rb:{get:function(){return 8192===
(this.mode&61440)}}}));a=new yb(a,b,c,d);wb(a);return a}function L(a){return 16384===(a&61440)}var zb={r:0,rs:1052672,"r+":2,w:577,wx:705,xw:705,"w+":578,"wx+":706,"xw+":706,a:1089,ax:1217,xa:1217,"a+":1090,"ax+":1218,"xa+":1218};function Ab(a){var b=["r","w","rw"][a&3];a&512&&(b+="w");return b}function xb(a,b){if(tb)return 0;if(-1===b.indexOf("r")||a.mode&292){if(-1!==b.indexOf("w")&&!(a.mode&146)||-1!==b.indexOf("x")&&!(a.mode&73))return 13}else return 13;return 0}
function Bb(a,b){try{return nb(a,b),17}catch(c){}return xb(a,"wx")}function Cb(a){var b=4096;for(a=a||0;a<=b;a++)if(!rb[a])return a;throw new I(24);}function Db(a,b){Eb||(Eb=function(){},Eb.prototype={},Object.defineProperties(Eb.prototype,{object:{get:function(){return this.node},set:function(a){this.node=a}}}));var c=new Eb,d;for(d in a)c[d]=a[d];a=c;b=Cb(b);a.fd=b;return rb[b]=a}var kb={open:function(a){a.Aa=qb[a.node.rdev].Aa;a.Aa.open&&a.Aa.open(a)},La:function(){throw new I(29);}};
function db(a,b){qb[a]={Aa:b}}function Fb(a,b){var c="/"===b,d=!b;if(c&&pb)throw new I(16);if(!c&&!d){var f=P(b,{xb:!1});b=f.path;f=f.node;if(f.Wa)throw new I(16);if(!L(f.mode))throw new I(20);}b={type:a,jb:{},Cb:b,Vb:[]};a=a.Ga(b);a.Ga=b;b.root=a;c?pb=a:f&&(f.Wa=b,f.Ga&&f.Ga.Vb.push(b))}function Gb(a,b,c){var d=P(a,{parent:!0}).node;a=Za(a);if(!a||"."===a||".."===a)throw new I(22);var f=Bb(d,a);if(f)throw new I(f);if(!d.za.Va)throw new I(1);return d.za.Va(d,a,b,c)}
function R(a,b){return Gb(a,(void 0!==b?b:511)&1023|16384,0)}function Hb(a,b,c){"undefined"===typeof c&&(c=b,b=438);return Gb(a,b|8192,c)}function Ib(a,b){if(!ab(a))throw new I(2);var c=P(b,{parent:!0}).node;if(!c)throw new I(2);b=Za(b);var d=Bb(c,b);if(d)throw new I(d);if(!c.za.symlink)throw new I(1);return c.za.symlink(c,b,a)}
function Jb(a){var b=P(a,{parent:!0}).node,c=Za(a),d=nb(b,c);a:{try{var f=nb(b,c)}catch(h){f=h.Ea;break a}var g=xb(b,"wx");f=g?g:L(f.mode)?21:0}if(f)throw new I(f);if(!b.za.unlink)throw new I(1);if(d.Wa)throw new I(16);try{O.willDeletePath&&O.willDeletePath(a)}catch(h){console.log("FS.trackingDelegate['willDeletePath']('"+a+"') threw an exception: "+h.message)}b.za.unlink(b,c);b=vb(d.parent.id,d.name);if(N[b]===d)N[b]=d.Sa;else for(b=N[b];b;){if(b.Sa===d){b.Sa=d.Sa;break}b=b.Sa}try{if(O.onDeletePath)O.onDeletePath(a)}catch(h){console.log("FS.trackingDelegate['onDeletePath']('"+
a+"') threw an exception: "+h.message)}}function ub(a){a=P(a).node;if(!a)throw new I(2);if(!a.za.readlink)throw new I(22);return ab(Q(a.parent),a.za.readlink(a))}function Kb(a,b){var c;"string"===typeof a?c=P(a,{Ua:!0}).node:c=a;if(!c.za.Fa)throw new I(1);c.za.Fa(c,{mode:b&4095|c.mode&-4096,timestamp:Date.now()})}
function Lb(a,b,c,d){if(""===a)throw new I(2);if("string"===typeof b){var f=zb[b];if("undefined"===typeof f)throw Error("Unknown file open mode: "+b);b=f}c=b&64?("undefined"===typeof c?438:c)&4095|32768:0;if("object"===typeof a)var g=a;else{a=Xa(a);try{g=P(a,{Ua:!(b&131072)}).node}catch(l){}}f=!1;if(b&64)if(g){if(b&128)throw new I(17);}else g=Gb(a,c,0),f=!0;if(!g)throw new I(2);8192===(g.mode&61440)&&(b&=-513);if(b&65536&&!L(g.mode))throw new I(20);if(!f&&(c=g?40960===(g.mode&61440)?40:L(g.mode)&&
("r"!==Ab(b)||b&512)?21:xb(g,Ab(b)):2))throw new I(c);if(b&512){c=g;var h;"string"===typeof c?h=P(c,{Ua:!0}).node:h=c;if(!h.za.Fa)throw new I(1);if(L(h.mode))throw new I(21);if(32768!==(h.mode&61440))throw new I(22);if(c=xb(h,"w"))throw new I(c);h.za.Fa(h,{size:0,timestamp:Date.now()})}b&=-641;d=Db({node:g,path:Q(g),flags:b,seekable:!0,position:0,Aa:g.Aa,ec:[],error:!1},d);d.Aa.open&&d.Aa.open(d);!e.logReadFiles||b&1||(Mb||(Mb={}),a in Mb||(Mb[a]=1,console.log("FS.trackingDelegate error on read file: "+
a)));try{O.onOpenFile&&(g=0,1!==(b&2097155)&&(g|=1),0!==(b&2097155)&&(g|=2),O.onOpenFile(a,g))}catch(l){console.log("FS.trackingDelegate['onOpenFile']('"+a+"', flags) threw an exception: "+l.message)}return d}function Nb(a){if(null===a.fd)throw new I(9);a.Oa&&(a.Oa=null);try{a.Aa.close&&a.Aa.close(a)}catch(b){throw b;}finally{rb[a.fd]=null}a.fd=null}
function Ob(a,b,c){if(null===a.fd)throw new I(9);if(!a.seekable||!a.Aa.La)throw new I(29);if(0!=c&&1!=c&&2!=c)throw new I(22);a.position=a.Aa.La(a,b,c);a.ec=[]}
function Pb(a,b,c,d,f,g){if(0>d||0>f)throw new I(22);if(null===a.fd)throw new I(9);if(0===(a.flags&2097155))throw new I(9);if(L(a.node.mode))throw new I(21);if(!a.Aa.write)throw new I(22);a.flags&1024&&Ob(a,0,2);var h="undefined"!==typeof f;if(!h)f=a.position;else if(!a.seekable)throw new I(29);b=a.Aa.write(a,b,c,d,f,g);h||(a.position+=b);try{if(a.path&&O.onWriteToFile)O.onWriteToFile(a.path)}catch(l){console.log("FS.trackingDelegate['onWriteToFile']('"+a.path+"') threw an exception: "+l.message)}return b}
function Qb(){I||(I=function(a,b){this.node=b;this.Zb=function(a){this.Ea=a};this.Zb(a);this.message="FS error";this.stack&&Object.defineProperty(this,"stack",{value:Error().stack,writable:!0})},I.prototype=Error(),I.prototype.constructor=I,[2].forEach(function(a){mb[a]=new I(a);mb[a].stack="<generic error, no stack>"}))}var Rb;function Sb(a,b){var c=0;a&&(c|=365);b&&(c|=146);return c}function Tb(a,b,c,d){a=H("string"===typeof a?a:Q(a),b);return R(a,Sb(c,d))}
function Ub(a,b){a="string"===typeof a?a:Q(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=H(a,c);try{R(d)}catch(f){}a=d}}return d}function Wb(a,b,c,d){a=H("string"===typeof a?a:Q(a),b);c=Sb(c,d);return Gb(a,(void 0!==c?c:438)&4095|32768,0)}
function Xb(a,b,c,d,f,g){a=b?H("string"===typeof a?a:Q(a),b):a;d=Sb(d,f);f=Gb(a,(void 0!==d?d:438)&4095|32768,0);if(c){if("string"===typeof c){a=Array(c.length);b=0;for(var h=c.length;b<h;++b)a[b]=c.charCodeAt(b);c=a}Kb(f,d|146);a=Lb(f,"w");Pb(a,c,0,c.length,0,g);Nb(a);Kb(f,d)}return f}
function S(a,b,c,d){a=H("string"===typeof a?a:Q(a),b);b=Sb(!!c,!!d);S.Bb||(S.Bb=64);var f=S.Bb++<<8|0;db(f,{open:function(a){a.seekable=!1},close:function(){d&&d.buffer&&d.buffer.length&&d(10)},read:function(a,b,d,f){for(var g=0,h=0;h<f;h++){try{var m=c()}catch(D){throw new I(5);}if(void 0===m&&0===g)throw new I(11);if(null===m||void 0===m)break;g++;b[d+h]=m}g&&(a.node.timestamp=Date.now());return g},write:function(a,b,c,f){for(var g=0;g<f;g++)try{d(b[c+g])}catch(v){throw new I(5);}f&&(a.node.timestamp=
Date.now());return g}});return Hb(a,b,f)}function Yb(a,b,c){a=H("string"===typeof a?a:Q(a),b);return Ib(c,a)}
function Zb(a){if(a.Rb||a.Sb||a.link||a.ya)return!0;var b=!0;if("undefined"!==typeof XMLHttpRequest)throw Error("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");if(e.read)try{a.ya=hb(e.read(a.url),!0),a.Ba=a.ya.length}catch(c){b=!1}else throw Error("Cannot load without read() or XMLHttpRequest.");b||Va(5);return b}
function $b(a,b,c,d,f){function g(){this.ib=!1;this.Ya=[]}g.prototype.get=function(a){if(!(a>this.length-1||0>a)){var b=a%this.chunkSize;return this.Ab(a/this.chunkSize|0)[b]}};g.prototype.Yb=function(a){this.Ab=a};g.prototype.tb=function(){var a=new XMLHttpRequest;a.open("HEAD",c,!1);a.send(null);if(!(200<=a.status&&300>a.status||304===a.status))throw Error("Couldn't load "+c+". Status: "+a.status);var b=Number(a.getResponseHeader("Content-length")),d,f=(d=a.getResponseHeader("Accept-Ranges"))&&
"bytes"===d;a=(d=a.getResponseHeader("Content-Encoding"))&&"gzip"===d;var g=1048576;f||(g=b);var h=this;h.Yb(function(a){var d=a*g,f=(a+1)*g-1;f=Math.min(f,b-1);if("undefined"===typeof h.Ya[a]){var z=h.Ya;if(d>f)throw Error("invalid range ("+d+", "+f+") or no bytes requested!");if(f>b-1)throw Error("only "+b+" bytes available! programmer error!");var m=new XMLHttpRequest;m.open("GET",c,!1);b!==g&&m.setRequestHeader("Range","bytes="+d+"-"+f);"undefined"!=typeof Uint8Array&&(m.responseType="arraybuffer");
m.overrideMimeType&&m.overrideMimeType("text/plain; charset=x-user-defined");m.send(null);if(!(200<=m.status&&300>m.status||304===m.status))throw Error("Couldn't load "+c+". Status: "+m.status);d=void 0!==m.response?new Uint8Array(m.response||[]):hb(m.responseText||"",!0);z[a]=d}if("undefined"===typeof h.Ya[a])throw Error("doXHR failed!");return h.Ya[a]});if(a||!b)g=b=1,g=b=this.Ab(0).length,console.log("LazyFiles on gzip forces download of the whole file when length is accessed");this.Lb=b;this.Kb=
g;this.ib=!0};if("undefined"!==typeof XMLHttpRequest){if(!q)throw"Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc";var h=new g;Object.defineProperties(h,{length:{get:function(){this.ib||this.tb();return this.Lb}},chunkSize:{get:function(){this.ib||this.tb();return this.Kb}}});var l=void 0}else l=c,h=void 0;var p=Wb(a,b,d,f);h?p.ya=h:l&&(p.ya=null,p.url=l);Object.defineProperties(p,{Ba:{get:function(){return this.ya.length}}});var t=
{};Object.keys(p.Aa).forEach(function(a){var b=p.Aa[a];t[a]=function(){if(!Zb(p))throw new I(5);return b.apply(null,arguments)}});t.read=function(a,b,c,d,f){if(!Zb(p))throw new I(5);a=a.node.ya;if(f>=a.length)return 0;d=Math.min(a.length-f,d);if(a.slice)for(var z=0;z<d;z++)b[c+z]=a[f+z];else for(z=0;z<d;z++)b[c+z]=a.get(f+z);return d};p.Aa=t;return p}
function ac(a,b,c,d,f,g,h,l,p,t){function v(c){function z(c){t&&t();l||Xb(a,b,c,d,f,p);g&&g();Ma(D)}var Y=!1;e.preloadPlugins.forEach(function(a){!Y&&a.canHandle(m)&&(a.handle(c,m,z,function(){h&&h();Ma(D)}),Y=!0)});Y||z(c)}(void 0).pe();var m=b?ab(H(a,b)):a,D="cp "+m;La(D);"string"==typeof c?(void 0).le(c,function(a){v(a)},h):v(c)}
var T={},yb,Eb,Mb,J={Jb:1,Hb:2,Zd:3,Qc:4,nb:5,qb:6,fc:7,sd:8,mb:9,wc:10,Gb:11,ie:11,ob:12,hc:13,Jc:14,Ed:15,uc:16,Ic:17,je:18,eb:19,Ib:20,Sc:21,Ja:22,nd:23,dd:24,Qa:25,fe:26,Kc:27,Ad:28,Yd:29,Vd:30,ed:31,Od:32,Fc:33,Sd:34,wd:42,Nc:43,xc:44,Uc:45,Vc:46,Wc:47,bd:48,ge:49,qd:50,Tc:51,Cc:35,td:37,nc:52,qc:53,ke:54,od:55,rc:56,sc:57,Dc:35,tc:59,Cd:60,rd:61,ce:62,Bd:63,xd:64,yd:65,Ud:66,ud:67,kc:68,$d:69,yc:70,Pd:71,hd:72,Gc:73,pc:74,Jd:76,oc:77,Td:78,Xc:79,Yc:80,ad:81,$c:82,Zc:83,Dd:38,pb:39,jd:36,cd:40,
Kd:95,Nd:96,Bc:104,pd:105,lc:97,Rd:91,Hd:88,zd:92,Wd:108,Ac:111,ic:98,zc:103,md:101,kd:100,de:110,Lc:112,Mc:113,Pc:115,mc:114,Ec:89,gd:90,Qd:93,Xd:94,jc:99,ld:102,Rc:106,Fd:107,ee:109,he:87,Hc:122,ae:116,Id:95,vd:123,Oc:84,Ld:75,vc:125,Gd:131,Md:130,be:86},bc={};
function cc(a,b){try{var c=P(a,{Ua:!0}).node;if(!c)throw new I(2);if(!c.za.Ia)throw new I(1);var d=c.za.Ia(c)}catch(f){if(f&&f.node&&Xa(a)!==Xa(Q(f.node)))return-J.Ib;throw f;}A[b>>2]=d.dev;A[b+4>>2]=0;A[b+8>>2]=d.ino;A[b+12>>2]=d.mode;A[b+16>>2]=d.nlink;A[b+20>>2]=d.uid;A[b+24>>2]=d.gid;A[b+28>>2]=d.rdev;A[b+32>>2]=0;A[b+36>>2]=d.size;A[b+40>>2]=4096;A[b+44>>2]=d.blocks;A[b+48>>2]=d.atime.getTime()/1E3|0;A[b+52>>2]=0;A[b+56>>2]=d.mtime.getTime()/1E3|0;A[b+60>>2]=0;A[b+64>>2]=d.ctime.getTime()/1E3|
0;A[b+68>>2]=0;A[b+72>>2]=d.ino;return 0}var U=0;function V(){U+=4;return A[U-4>>2]}function W(){var a=rb[V()];if(!a)throw new I(J.mb);return a}function xa(){return y.length}function dc(){w("OOM")}function ec(a){if(0===a)return 0;a=C(a);if(!G.hasOwnProperty(a))return 0;ec.Da&&X(ec.Da);a=G[a];var b=Aa(a)+1,c=F(b);c&&ra(a,y,c,b);ec.Da=c;return ec.Da}function fc(){fc.Da||(fc.Da=[]);fc.Da.push(sa());return fc.Da.length-1}function hc(a){return 0===a%4&&(0!==a%100||0===a%400)}
function ic(a,b){for(var c=0,d=0;d<=b;c+=a[d++]);return c}var jc=[31,29,31,30,31,30,31,31,30,31,30,31],kc=[31,28,31,30,31,30,31,31,30,31,30,31];function lc(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),d=(hc(a.getFullYear())?jc:kc)[c];if(b>d-a.getDate())b-=d-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function mc(a,b,c,d){function f(a,b,c){for(a="number"===typeof a?a.toString():a||"";a.length<b;)a=c[0]+a;return a}function g(a,b){return f(a,b,"0")}function h(a,b){function c(a){return 0>a?-1:0<a?1:0}var d;0===(d=c(a.getFullYear()-b.getFullYear()))&&0===(d=c(a.getMonth()-b.getMonth()))&&(d=c(a.getDate()-b.getDate()));return d}function l(a){switch(a.getDay()){case 0:return new Date(a.getFullYear()-1,11,29);case 1:return a;case 2:return new Date(a.getFullYear(),0,3);case 3:return new Date(a.getFullYear(),
0,2);case 4:return new Date(a.getFullYear(),0,1);case 5:return new Date(a.getFullYear()-1,11,31);case 6:return new Date(a.getFullYear()-1,11,30)}}function p(a){a=lc(new Date(a.Ca+1900,0,1),a.cb);var b=l(new Date(a.getFullYear()+1,0,4));return 0>=h(l(new Date(a.getFullYear(),0,4)),a)?0>=h(b,a)?a.getFullYear()+1:a.getFullYear():a.getFullYear()-1}var t=A[d+40>>2];d={cc:A[d>>2],bc:A[d+4>>2],bb:A[d+8>>2],Pa:A[d+12>>2],Ma:A[d+16>>2],Ca:A[d+20>>2],Eb:A[d+24>>2],cb:A[d+28>>2],re:A[d+32>>2],ac:A[d+36>>2],
dc:t?C(t):""};c=C(c);t={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S"};for(var v in t)c=c.replace(new RegExp(v,"g"),t[v]);var m="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),D="January February March April May June July August September October November December".split(" ");t={"%a":function(a){return m[a.Eb].substring(0,3)},"%A":function(a){return m[a.Eb]},"%b":function(a){return D[a.Ma].substring(0,
3)},"%B":function(a){return D[a.Ma]},"%C":function(a){return g((a.Ca+1900)/100|0,2)},"%d":function(a){return g(a.Pa,2)},"%e":function(a){return f(a.Pa,2," ")},"%g":function(a){return p(a).toString().substring(2)},"%G":function(a){return p(a)},"%H":function(a){return g(a.bb,2)},"%I":function(a){a=a.bb;0==a?a=12:12<a&&(a-=12);return g(a,2)},"%j":function(a){return g(a.Pa+ic(hc(a.Ca+1900)?jc:kc,a.Ma-1),3)},"%m":function(a){return g(a.Ma+1,2)},"%M":function(a){return g(a.bc,2)},"%n":function(){return"\n"},
"%p":function(a){return 0<=a.bb&&12>a.bb?"AM":"PM"},"%S":function(a){return g(a.cc,2)},"%t":function(){return"\t"},"%u":function(a){return(new Date(a.Ca+1900,a.Ma+1,a.Pa,0,0,0,0)).getDay()||7},"%U":function(a){var b=new Date(a.Ca+1900,0,1),c=0===b.getDay()?b:lc(b,7-b.getDay());a=new Date(a.Ca+1900,a.Ma,a.Pa);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(ic(hc(a.getFullYear())?jc:kc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":"00"},"%V":function(a){var b=l(new Date(a.Ca+1900,0,4)),c=l(new Date(a.Ca+
1901,0,4)),d=lc(new Date(a.Ca+1900,0,1),a.cb);return 0>h(d,b)?"53":0>=h(c,d)?"01":g(Math.ceil((b.getFullYear()<a.Ca+1900?a.cb+32-b.getDate():a.cb+1-b.getDate())/7),2)},"%w":function(a){return(new Date(a.Ca+1900,a.Ma+1,a.Pa,0,0,0,0)).getDay()},"%W":function(a){var b=new Date(a.Ca,0,1),c=1===b.getDay()?b:lc(b,0===b.getDay()?1:7-b.getDay()+1);a=new Date(a.Ca+1900,a.Ma,a.Pa);return 0>h(c,a)?g(Math.ceil((31-c.getDate()+(ic(hc(a.getFullYear())?jc:kc,a.getMonth()-1)-31)+a.getDate())/7),2):0===h(c,b)?"01":
"00"},"%y":function(a){return(a.Ca+1900).toString().substring(2)},"%Y":function(a){return a.Ca+1900},"%z":function(a){a=a.ac;var b=0<=a;a=Math.abs(a)/60;return(b?"+":"-")+String("0000"+(a/60*100+a%60)).slice(-4)},"%Z":function(a){return a.dc},"%%":function(){return"%"}};for(v in t)0<=c.indexOf(v)&&(c=c.replace(new RegExp(v,"g"),t[v](d)));v=hb(c,!1);if(v.length>b)return 0;y.set(v,a);return v.length-1}Qb();N=Array(4096);Fb(K,"/");R("/tmp");R("/home");R("/home/web_user");
(function(){R("/dev");db(259,{read:function(){return 0},write:function(a,b,c,h){return h}});Hb("/dev/null",259);cb(1280,ib);cb(1536,jb);Hb("/dev/tty",1280);Hb("/dev/tty1",1536);if("object"===typeof crypto&&"function"===typeof crypto.getRandomValues){var a=new Uint8Array(1);var b=function(){crypto.getRandomValues(a);return a[0]}}else if(r)try{var c=require("crypto");b=function(){return c.randomBytes(1)[0]}}catch(d){}b||(b=function(){w("random_device")});S("/dev","random",b);S("/dev","urandom",b);R("/dev/shm");
R("/dev/shm/tmp")})();R("/proc");R("/proc/self");R("/proc/self/fd");Fb({Ga:function(){var a=lb("/proc/self","fd",16895,73);a.za={lookup:function(a,c){var b=rb[+c];if(!b)throw new I(9);a={parent:null,Ga:{Cb:"fake"},za:{readlink:function(){return b.path}}};return a.parent=a}};return a}},"/proc/self/fd");e.FS_createFolder=Tb;e.FS_createPath=Ub;e.FS_createDataFile=Xb;e.FS_createPreloadedFile=ac;e.FS_createLazyFile=$b;e.FS_createLink=Yb;e.FS_createDevice=S;e.FS_unlink=Jb;
if(r){var fs=require("fs"),ob=require("path");M.$b()}function hb(a,b){var c=Array(Aa(a)+1);a=ra(a,c,0,c.length);b&&(c.length=a);return c}
var qc=e.asm({},{e:w,l:function(a,b,c,d){w("Assertion failed: "+C(a)+", at: "+[b?C(b):"unknown filename",c,d?C(d):"unknown function"])},B:Ua,d:function(a){return F(a)},c:function(a){"uncaught_exception"in nc?nc.Fb++:nc.Fb=1;throw a;},t:function(){return!!nc.Fb},n:function(){},s:function(){Va(1);return-1},m:Va,r:function(a,b){U=b;try{var c=W();V();var d=V(),f=V(),g=V();Ob(c,d,g);A[f>>2]=c.position;c.Oa&&0===d&&0===g&&(c.Oa=null);return 0}catch(h){return"undefined"!==typeof T&&h instanceof I||w(h),
-h.Ea}},G:function(a,b){U=b;try{var c=W(),d=V();a:{var f=V();for(b=a=0;b<f;b++){var g=A[d+(8*b+4)>>2],h=c,l=A[d+8*b>>2],p=g,t=void 0,v=y;if(0>p||0>t)throw new I(22);if(null===h.fd)throw new I(9);if(1===(h.flags&2097155))throw new I(9);if(L(h.node.mode))throw new I(21);if(!h.Aa.read)throw new I(22);var m="undefined"!==typeof t;if(!m)t=h.position;else if(!h.seekable)throw new I(29);var D=h.Aa.read(h,v,l,p,t);m||(h.position+=D);var z=D;if(0>z){var fb=-1;break a}a+=z;if(z<g)break}fb=a}return fb}catch(Y){return"undefined"!==
typeof T&&Y instanceof I||w(Y),-Y.Ea}},q:function(a,b){U=b;try{var c=W(),d=V();a:{var f=V();for(b=a=0;b<f;b++){var g=Pb(c,y,A[d+8*b>>2],A[d+(8*b+4)>>2],void 0);if(0>g){var h=-1;break a}a+=g}h=a}return h}catch(l){return"undefined"!==typeof T&&l instanceof I||w(l),-l.Ea}},F:function(a,b){U=b;try{var c=V(),d=V(),f=V(),g=V(),h=V(),l=V();l<<=12;a=!1;if(-1===h){var p=oc(16384,d);if(!p)return-J.ob;pc(p,0,d);a=!0}else{var t=rb[h];if(!t)return-J.mb;b=B;if(1===(t.flags&2097155))throw new I(13);if(!t.Aa.$a)throw new I(19);
var v=t.Aa.$a(t,b,c,d,l,f,g);p=v.Wb;a=v.fb}bc[p]={Ub:p,Tb:d,fb:a,fd:h,flags:g};return p}catch(m){return"undefined"!==typeof T&&m instanceof I||w(m),-m.Ea}},E:function(a,b){U=b;try{var c=C(V()),d=V();return cc(c,d)}catch(f){return"undefined"!==typeof T&&f instanceof I||w(f),-f.Ea}},D:function(a,b){U=b;try{var c=W(),d=V();return cc(c.path,d)}catch(f){return"undefined"!==typeof T&&f instanceof I||w(f),-f.Ea}},C:function(a,b){U=b;try{var c=W(),d=V(),f=V();if(!c.Oa){var g=P(c.path,{Ua:!0}).node;if(!g.za.readdir)throw new I(20);
var h=g.za.readdir(g);c.Oa=h}for(a=0;0<c.Oa.length&&a+268<=f;){var l=c.Oa.pop();if("."===l[0]){var p=1;var t=4}else{var v=nb(c.node,l);p=v.id;t=8192===(v.mode&61440)?2:L(v.mode)?4:40960===(v.mode&61440)?10:8}A[d+a>>2]=p;A[d+a+4>>2]=c.position;ja[d+a+8>>1]=268;y[d+a+10>>0]=t;ra(l,B,d+a+11,256);a+=268}return a}catch(m){return"undefined"!==typeof T&&m instanceof I||w(m),-m.Ea}},i:function(a,b){U=b;try{var c=W();switch(V()){case 0:var d=V();return 0>d?-J.Ja:Lb(c.path,c.flags,0,d).fd;case 1:case 2:return 0;
case 3:return c.flags;case 4:return d=V(),c.flags|=d,0;case 12:return d=V(),ja[d+0>>1]=2,0;case 13:case 14:return 0;case 16:case 8:return-J.Ja;case 9:return Va(J.Ja),-1;default:return-J.Ja}}catch(f){return"undefined"!==typeof T&&f instanceof I||w(f),-f.Ea}},p:function(a,b){U=b;try{var c=C(V()),d=V(),f=V();return Lb(c,d,f).fd}catch(g){return"undefined"!==typeof T&&g instanceof I||w(g),-g.Ea}},o:function(a,b){U=b;try{var c=W(),d=V();switch(d){case 21509:case 21505:return c.tty?0:-J.Qa;case 21510:case 21511:case 21512:case 21506:case 21507:case 21508:return c.tty?
0:-J.Qa;case 21519:if(!c.tty)return-J.Qa;var f=V();return A[f>>2]=0;case 21520:return c.tty?-J.Ja:-J.Qa;case 21531:a=f=V();if(!c.Aa.Qb)throw new I(25);return c.Aa.Qb(c,d,a);case 21523:return c.tty?0:-J.Qa;case 21524:return c.tty?0:-J.Qa;default:w("bad ioctl syscall "+d)}}catch(g){return"undefined"!==typeof T&&g instanceof I||w(g),-g.Ea}},k:function(a,b){U=b;try{var c=W();Nb(c);return 0}catch(d){return"undefined"!==typeof T&&d instanceof I||w(d),-d.Ea}},A:function(a,b){U=b;try{var c=V(),d=V(),f=bc[c];
if(!f)return 0;if(d===f.Tb){var g=rb[f.fd],h=f.flags,l=new Uint8Array(B.subarray(c,c+d));g&&g.Aa.ab&&g.Aa.ab(g,l,0,d,h);bc[c]=null;f.fb&&X(f.Ub)}return 0}catch(p){return"undefined"!==typeof T&&p instanceof I||w(p),-p.Ea}},j:function(){},b:function(){e.abort()},z:xa,y:function(a,b,c){B.set(B.subarray(b,b+c),a)},x:function(a){dc(a)},h:ec,g:function(a){var b=fc.Da[a];fc.Da.splice(a,1);ta(b)},f:fc,w:function(){return 0},v:function(a,b,c,d){return mc(a,b,c,d)},u:dc,a:wa},buffer);e.asm=qc;
var nc=e.__ZSt18uncaught_exceptionv=function(){return e.asm.H.apply(null,arguments)};e.___errno_location=function(){return e.asm.I.apply(null,arguments)};var X=e._free=function(){return e.asm.J.apply(null,arguments)},F=e._malloc=function(){return e.asm.K.apply(null,arguments)},oc=e._memalign=function(){return e.asm.L.apply(null,arguments)},pc=e._memset=function(){return e.asm.M.apply(null,arguments)};e._voikkoAnalyzeWordCstr=function(){return e.asm.N.apply(null,arguments)};
e._voikkoFreeCstr=function(){return e.asm.O.apply(null,arguments)};e._voikkoFreeCstrArray=function(){return e.asm.P.apply(null,arguments)};e._voikkoFreeErrorMessageCstr=function(){return e.asm.Q.apply(null,arguments)};e._voikkoFreeGrammarError=function(){return e.asm.R.apply(null,arguments)};e._voikkoGetGrammarErrorCode=function(){return e.asm.S.apply(null,arguments)};e._voikkoGetGrammarErrorLength=function(){return e.asm.T.apply(null,arguments)};
e._voikkoGetGrammarErrorShortDescription=function(){return e.asm.U.apply(null,arguments)};e._voikkoGetGrammarErrorStartPos=function(){return e.asm.V.apply(null,arguments)};e._voikkoGetGrammarErrorSuggestions=function(){return e.asm.W.apply(null,arguments)};e._voikkoGetVersion=function(){return e.asm.X.apply(null,arguments)};e._voikkoHyphenateCstr=function(){return e.asm.Y.apply(null,arguments)};e._voikkoInit=function(){return e.asm.Z.apply(null,arguments)};
e._voikkoInsertHyphensCstr=function(){return e.asm._.apply(null,arguments)};e._voikkoNextGrammarErrorCstr=function(){return e.asm.$.apply(null,arguments)};e._voikkoNextSentenceStartCstr=function(){return e.asm.aa.apply(null,arguments)};e._voikkoNextTokenCstr=function(){return e.asm.ba.apply(null,arguments)};e._voikkoSetBooleanOption=function(){return e.asm.ca.apply(null,arguments)};e._voikkoSetIntegerOption=function(){return e.asm.da.apply(null,arguments)};
e._voikkoSpellCstr=function(){return e.asm.ea.apply(null,arguments)};e._voikkoSuggestCstr=function(){return e.asm.fa.apply(null,arguments)};e._voikkoTerminate=function(){return e.asm.ga.apply(null,arguments)};e._voikko_dict_description=function(){return e.asm.ha.apply(null,arguments)};e._voikko_dict_language=function(){return e.asm.ia.apply(null,arguments)};e._voikko_dict_script=function(){return e.asm.ja.apply(null,arguments)};e._voikko_dict_variant=function(){return e.asm.ka.apply(null,arguments)};
e._voikko_free_dicts=function(){return e.asm.la.apply(null,arguments)};e._voikko_free_mor_analysis=function(){return e.asm.ma.apply(null,arguments)};e._voikko_free_mor_analysis_value_cstr=function(){return e.asm.na.apply(null,arguments)};e._voikko_list_dicts=function(){return e.asm.oa.apply(null,arguments)};e._voikko_mor_analysis_keys=function(){return e.asm.pa.apply(null,arguments)};e._voikko_mor_analysis_value_cstr=function(){return e.asm.qa.apply(null,arguments)};
var Ta=e.globalCtors=function(){return e.asm.ta.apply(null,arguments)},qa=e.stackAlloc=function(){return e.asm.ua.apply(null,arguments)},ta=e.stackRestore=function(){return e.asm.va.apply(null,arguments)},sa=e.stackSave=function(){return e.asm.wa.apply(null,arguments)};e.dynCall_v=function(){return e.asm.ra.apply(null,arguments)};e.dynCall_vi=function(){return e.asm.sa.apply(null,arguments)};e.asm=qc;e.getMemory=ua;e.addRunDependency=La;e.removeRunDependency=Ma;e.FS_createFolder=Tb;
e.FS_createPath=Ub;e.FS_createDataFile=Xb;e.FS_createPreloadedFile=ac;e.FS_createLazyFile=$b;e.FS_createLink=Yb;e.FS_createDevice=S;e.FS_unlink=Jb;e.then=function(a){if(e.calledRun)a(e);else{var b=e.onRuntimeInitialized;e.onRuntimeInitialized=function(){b&&b();a(e)}}return e};function fa(a){this.name="ExitStatus";this.message="Program terminated with exit("+a+")";this.status=a}fa.prototype=Error();fa.prototype.constructor=fa;Ka=function rc(){e.calledRun||sc();e.calledRun||(Ka=rc)};
function sc(){function a(){if(!e.calledRun&&(e.calledRun=!0,!na)){va||(va=!0,e.noFSInit||Rb||(Rb=!0,Qb(),e.stdin=e.stdin,e.stdout=e.stdout,e.stderr=e.stderr,e.stdin?S("/dev","stdin",e.stdin):Ib("/dev/tty","/dev/stdin"),e.stdout?S("/dev","stdout",null,e.stdout):Ib("/dev/tty","/dev/stdout"),e.stderr?S("/dev","stderr",null,e.stderr):Ib("/dev/tty1","/dev/stderr"),Lb("/dev/stdin","r"),Lb("/dev/stdout","w"),Lb("/dev/stderr","w")),Ca(Ea));tb=!1;Ca(Fa);if(e.onRuntimeInitialized)e.onRuntimeInitialized();if(e.postRun)for("function"==
typeof e.postRun&&(e.postRun=[e.postRun]);e.postRun.length;){var a=e.postRun.shift();Ga.unshift(a)}Ca(Ga)}}if(!(0<Ia)){if(e.preRun)for("function"==typeof e.preRun&&(e.preRun=[e.preRun]);e.preRun.length;)Ha();Ca(Da);0<Ia||e.calledRun||(e.setStatus?(e.setStatus("Running..."),setTimeout(function(){setTimeout(function(){e.setStatus("")},1);a()},1)):a())}}e.run=sc;
function w(a){if(e.onAbort)e.onAbort(a);void 0!==a?(ha(a),k(a),a=JSON.stringify(a)):a="";na=!0;throw"abort("+a+"). Build with -s ASSERTIONS=1 for more info.";}e.abort=w;if(e.preInit)for("function"==typeof e.preInit&&(e.preInit=[e.preInit]);0<e.preInit.length;)e.preInit.pop()();e.noExitRuntime=!0;sc();
var tc=E("voikkoInit","number",["number","string","string"]),uc=E("voikkoTerminate",null,["number"]),vc=E("voikkoSetBooleanOption","number",["number","number","number"]),wc=E("voikkoSetIntegerOption","number",["number","number","number"]),xc=E("voikkoSpellCstr","number",["number","string"]),yc=E("voikkoSuggestCstr","number",["number","string"]),zc=E("voikkoHyphenateCstr","number",["number","string"]),Ac=E("voikkoInsertHyphensCstr","number",["number","string","string","number"]),Bc=E("voikkoFreeCstrArray",
null,["number"]),Cc=E("voikkoFreeCstr",null,["number"]),Dc=E("voikkoNextTokenCstr","number",["number","number","number","number"]),Ec=E("voikkoNextSentenceStartCstr","number",["number","number","number","number"]),Fc=E("voikkoNextGrammarErrorCstr","number",["number","string","number","number","number"]),Gc=E("voikkoGetGrammarErrorCode","number",["number"]),Hc=E("voikkoGetGrammarErrorStartPos","number",["number"]),Ic=E("voikkoGetGrammarErrorLength","number",["number"]),Jc=E("voikkoGetGrammarErrorSuggestions",
"number",["number"]),Kc=E("voikkoFreeGrammarError",null,["number"]),Lc=E("voikkoGetGrammarErrorShortDescription","number",["number","string"]),Mc=E("voikkoFreeErrorMessageCstr",null,["number"]),Nc=E("voikkoAnalyzeWordCstr","number",["number","string"]),Oc=E("voikko_free_mor_analysis",null,["number"]),Pc=E("voikko_mor_analysis_keys","number",["number"]),Qc=E("voikko_mor_analysis_value_cstr","number",["number","number"]),Rc=E("voikko_free_mor_analysis_value_cstr",null,["number"]);
function Z(a){return-1==a.indexOf("\x00")}e.onRuntimeInitialized=function(){if("onLoad"in e)e.onLoad(e)};
e.init=function(a,b){function c(){if(null==p)throw"Attempt to use Voikko instance after terminate() was called";}function d(a,b,c){var d=Gc(a),f=Hc(a),m=Ic(a),h=Jc(a),l=[];h&&g(h,l);a=Lc(a,c);c=C(a);Mc(a);return{errorCode:d,startPos:b+f,errorLen:m,suggestions:l,shortDescription:c}}function f(a,b){c();if(0==vc(p,a,b?1:0))throw"Could not set boolean option "+a+" to value "+b+".";}function g(a,b){for(var c=x(a,"i32*");0!=c;)b.push(C(c)),a+=4,c=x(a,"i32*")}function h(a){var b=[],c=Aa(a),d=F(c+1);ra(a,
B,d,c+1);for(var f=0,g=0,h=F(4);0<c;){var m=Dc(p,d+f,c,h),l=x(h,"i32");m=t[m];l=a.substring(g,g+l);g+=l.length;var v=Aa(l);b.push({type:m,text:l});f+=v;c-=v}X(h);X(d);return b}var l=F(4),p=tc(l,a,b);if(!p)throw a=x(l,"i32*"),a=C(a),X(l),a;X(l);var t=["NONE","WORD","PUNCTUATION","WHITESPACE","UNKNOWN"],v=["NONE","NO_START","PROBABLE","POSSIBLE"];return{terminate:function(){p&&(uc(p),p=null)},spell:function(a){c();return Z(a)&&1==xc(p,a)},suggest:function(a){c();var b=[];if(!Z(a))return b;a=yc(p,a);
if(0==a)return b;g(a,b);Bc(a);return b},grammarErrors:function(a,b){c();var f=[];if(!Z(a))return f;var g=0;a=a.replace("\r","\n").split("\n");for(var h=0;h<a.length;h++){for(var m=a[h],l=f,D=m,t=g,v=b,Sc=Aa(D),Vb=0;;){var eb=Fc(p,D,Sc,0,Vb);if(!eb)break;l.push(d(eb,t,v));Kc(eb);Vb++}g+=m.length+1}return f},analyze:function(a){c();var b=[];if(!Z(a))return b;a=Nc(p,a);if(!a)return b;for(var d=a,f=x(d,"i32*");0!=f;){for(var g={},h=Pc(f),m=x(h,"i32*");0!=m;){var l=C(m);m=Qc(f,m);g[l]=C(m);Rc(m);h+=4;
m=x(h,"i32*")}b.push(g);d+=4;f=x(d,"i32*")}Oc(a);return b},tokens:function(a){c();for(var b=[],d=0,f=a.indexOf("\x00");-1!=f;f=a.indexOf("\x00",f+1))b.push.apply(b,h(a.substring(d,f))),b.push({type:"UNKNOWN",text:"\x00"}),d=f+1;b.push.apply(b,h(a.substring(d)));return b},sentences:function(a){c();var b=[];if(!Z(a))return b.push({text:a,nextStartType:"NONE"}),b;var d=Aa(a),f=F(d+1),g=f;ra(a,B,f,d+1);for(var h=F(4);0<d;){var m=Ec(p,g,d,h),l=x(h,"i32"),t=a.substring(0,l);b.push({text:t,nextStartType:v[m]});
a=a.substring(l);m=Aa(t);g+=m;d-=m}X(h);X(f);return b},getHyphenationPattern:function(a){c();if(!Z(a)){for(var b="",d=0;d<a.length;d++)b+=" ";return b}a=zc(p,a);b=C(a);Cc(a);return b},hyphenate:function(a,b,d){void 0===b&&(b="-");void 0===d&&(d=!0);c();if(!Z(a)||!Z(b))return a;a=Ac(p,a,b,d?1:0);b=C(a);Cc(a);return b},setIgnoreDot:function(a){f(0,a)},setIgnoreNumbers:function(a){f(1,a)},setIgnoreUppercase:function(a){f(3,a)},setAcceptFirstUppercase:function(a){f(6,a)},setAcceptAllUppercase:function(a){f(7,
a)},setIgnoreNonwords:function(a){f(10,a)},setAcceptExtraHyphens:function(a){f(11,a)},setAcceptMissingHyphens:function(a){f(12,a)},setAcceptTitlesInGc:function(a){f(13,a)},setAcceptUnfinishedParagraphsInGc:function(a){f(14,a)},setAcceptBulletedListsInGc:function(a){f(16,a)},setNoUglyHyphenation:function(a){f(4,a)},setHyphenateUnknownWords:function(a){f(15,a)},setMinHyphenatedWordLength:function(a){c();if(0==wc(p,9,a))throw"Could not set integer option 9 to value "+a+".";},setSuggestionStrategy:function(a){if("TYPO"==
a)f(8,!1);else if("OCR"==a)f(8,!0);else throw"Unknown suggestion strategy "+a;}}};


  return Libvoikko
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
      module.exports = Libvoikko;
    else if (typeof define === 'function' && define['amd'])
      define([], function() { return Libvoikko; });
    else if (typeof exports === 'object')
      exports["Libvoikko"] = Libvoikko;
    